/****************************************************************************
**
** Metadata for AXVLC generated by dumpcpp from type library
** C:\Programme\VideoLAN\VLC\axvlc.dll
**
****************************************************************************/

#define QAX_DUMPCPP_AXVLC_NOINLINES
#include "axvlc.h"

using namespace AXVLC;

static const uint qt_meta_data_AXVLC__IVLCControl[] = {

 // content:
       1,       // revision
       0,       // classname
       0,    0, // classinfo
       25,    10, // methods
       13,    135, // properties
       1,    174, // enums/sets

 // signals: signature, parameters, type, tag, flags
       19, 40, 48, 49, 5,
       50, 89, 111, 112, 5,
       113, 138, 143, 144, 5,
       145, 171, 186, 187, 5,

 // slots: signature, parameters, type, tag, flags
       188, 206, 215, 216, 9,
       217, 235, 244, 245, 9,
       246, 262, 266, 267, 9,
       268, 288, 297, 298, 9,
       299, 312, 317, 318, 9,
       319, 336, 344, 345, 9,
       346, 361, 368, 369, 9,
       370, 418, 444, 445, 9,
       446, 459, 460, 461, 9,
       462, 483, 488, 497, 9,
       498, 506, 507, 508, 9,
       509, 516, 517, 518, 9,
       519, 532, 533, 534, 9,
       535, 548, 549, 550, 9,
       551, 567, 568, 569, 9,
       570, 585, 586, 587, 9,
       588, 603, 604, 605, 9,
       606, 636, 647, 648, 9,
       649, 662, 670, 671, 9,
       672, 679, 680, 681, 9,
       682, 695, 696, 697, 9,

 // properties: name, type, flags
       698, 707, 0x01005003, 		 // bool AutoLoop
       712, 721, 0x01005003, 		 // bool AutoPlay
       726, 733, 0x02004001, 		 // int Length
       737, 741, 0x0a005003, 		 // QString MRL
       749, 757, 0x01004001, 		 // bool Playing
       762, 776, 0x02005001, 		 // int PlaylistCount
       780, 794, 0x02005001, 		 // int PlaylistIndex
       798, 807, 0x06005003, 		 // double Position
       814, 819, 0x02005003, 		 // int Time
       823, 835, 0x0a004001, 		 // QString VersionInfo
       843, 851, 0x01005003, 		 // bool Visible
       856, 863, 0x02005003, 		 // int Volume
       867, 875, 0x0a055003, 		 // QString control

 // enums: name, flags, count, data
       883, 0x0, 7, 178, 

 // enum data: key, value
       899, AXVLC::VLCPlayListInsert,
       917, AXVLC::VLCPlayListInsertAndGo,
       940, AXVLC::VLCPlayListReplace,
       959, AXVLC::VLCPlayListReplaceAndGo,
       983, AXVLC::VLCPlayListAppend,
       1001, AXVLC::VLCPlayListAppendAndGo,
       1024, AXVLC::VLCPlayListCheckInsert,

        0        // eod
};

static const char qt_meta_enumstringdata_AXVLC[] = {
    "VLCPlaylistMode\0"
    "VLCPlayListInsert\0VLCPlayListInsertAndGo\0VLCPlayListReplace\0VLCPlayListReplaceAndGo\0VLCPlayListAppend\0VLCPlayListAppendAndGo\0VLCPlayListCheckInsert\0"

};

static const char *qt_meta_stringdata_AXVLC__IVLCControl() {
    static const char stringdata0[] = {
    "AXVLC::IVLCControl\0"
    "VisibleChanged(bool)\0Visible\0\0\0exception(int,QString,QString,QString)\0code,source,disc,help\0\0\0propertyChanged(QString)\0name\0\0\0signal(QString,int,void*)\0name,argc,argv\0\0\0"
    "SetAutoLoop(bool)\0AutoLoop\0\0\0SetAutoPlay(bool)\0"
    "AutoPlay\0\0\0SetMRL(QString)\0MRL\0\0\0SetPosition(double)\0Position\0\0\0SetTime(int)\0Time\0\0\0SetVisible(bool)\0Visible\0\0\0SetVolume(int)\0Volume\0\0\0addTarget(QString,QVariant,VLCPlaylistMode,int)\0uri,options,mode,Position\0"
    "\0\0fullscreen()\0\0\0\0getVariable(QString)\0name\0QVariant\0\0pause()\0\0\0\0play()\0\0\0\0playFaster()\0\0\0\0playSlower()\0\0\0\0playlistClear()\0\0\0\0playlistNext()\0\0\0\0playlistPrev()\0\0\0\0setVariable(QString,QVariant)\0name,value\0"
    "\0\0shuttle(int)\0seconds\0\0\0stop()\0\0\0\0toggleMute()\0\0\0\0"
    "AutoLoop\0bool\0AutoPlay\0bool\0Length\0int\0MRL\0QString\0Playing\0bool\0PlaylistCount\0int\0PlaylistIndex\0int\0Position\0double\0Time\0int\0VersionInfo\0QString\0Visible\0"
    "bool\0Volume\0int\0control\0QString\0"
    };
    static char data[sizeof(stringdata0) + sizeof(qt_meta_enumstringdata_AXVLC)];
    if (!data[0]) {
        int index = 0;
        memcpy(data + index, stringdata0, sizeof(stringdata0) - 1);
        index += sizeof(stringdata0) - 1;
        memcpy(data + index, qt_meta_enumstringdata_AXVLC, sizeof(qt_meta_enumstringdata_AXVLC));
    }

    return data;
};

const QMetaObject IVLCControl::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_AXVLC__IVLCControl(),
qt_meta_data_AXVLC__IVLCControl }
};

void *IVLCControl::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, qt_meta_stringdata_AXVLC__IVLCControl()))
        return static_cast<void*>(const_cast<IVLCControl*>(this));
    return QAxObject::qt_metacast(_clname);
}

static const uint qt_meta_data_AXVLC__IVLCAudio[] = {

 // content:
       1,       // revision
       0,       // classname
       0,    0, // classinfo
       8,    10, // methods
       5,    50, // properties
       1,    65, // enums/sets

 // signals: signature, parameters, type, tag, flags
       17, 56, 78, 79, 5,
       80, 105, 110, 111, 5,
       112, 138, 153, 154, 5,

 // slots: signature, parameters, type, tag, flags
       155, 170, 177, 178, 9,
       179, 195, 203, 204, 9,
       205, 219, 224, 225, 9,
       226, 240, 246, 247, 9,
       248, 261, 262, 263, 9,

 // properties: name, type, flags
       264, 271, 0x02005003, 		 // int Volume
       275, 283, 0x02005003, 		 // int channel
       287, 295, 0x0a055003, 		 // QString control
       303, 308, 0x01005003, 		 // bool mute
       313, 319, 0x02005003, 		 // int track

 // enums: name, flags, count, data
       323, 0x0, 7, 69, 

 // enum data: key, value
       339, AXVLC::VLCPlayListInsert,
       357, AXVLC::VLCPlayListInsertAndGo,
       380, AXVLC::VLCPlayListReplace,
       399, AXVLC::VLCPlayListReplaceAndGo,
       423, AXVLC::VLCPlayListAppend,
       441, AXVLC::VLCPlayListAppendAndGo,
       464, AXVLC::VLCPlayListCheckInsert,

        0        // eod
};

static const char *qt_meta_stringdata_AXVLC__IVLCAudio() {
    static const char stringdata0[] = {
    "AXVLC::IVLCAudio\0"
    "exception(int,QString,QString,QString)\0code,source,disc,help\0\0\0propertyChanged(QString)\0name\0\0\0signal(QString,int,void*)\0name,argc,argv\0\0\0"
    "SetVolume(int)\0Volume\0\0\0setChannel(int)\0channel\0\0\0setMute(bool)\0"
    "mute\0\0\0setTrack(int)\0track\0\0\0toggleMute()\0\0\0\0"
    "Volume\0int\0channel\0int\0control\0QString\0mute\0bool\0track\0int\0"
    };
    static char data[sizeof(stringdata0) + sizeof(qt_meta_enumstringdata_AXVLC)];
    if (!data[0]) {
        int index = 0;
        memcpy(data + index, stringdata0, sizeof(stringdata0) - 1);
        index += sizeof(stringdata0) - 1;
        memcpy(data + index, qt_meta_enumstringdata_AXVLC, sizeof(qt_meta_enumstringdata_AXVLC));
    }

    return data;
};

const QMetaObject IVLCAudio::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_AXVLC__IVLCAudio(),
qt_meta_data_AXVLC__IVLCAudio }
};

void *IVLCAudio::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, qt_meta_stringdata_AXVLC__IVLCAudio()))
        return static_cast<void*>(const_cast<IVLCAudio*>(this));
    return QAxObject::qt_metacast(_clname);
}

static const uint qt_meta_data_AXVLC__IVLCInput[] = {

 // content:
       1,       // revision
       0,       // classname
       0,    0, // classinfo
       6,    10, // methods
       8,    40, // properties
       1,    64, // enums/sets

 // signals: signature, parameters, type, tag, flags
       17, 56, 78, 79, 5,
       80, 105, 110, 111, 5,
       112, 138, 153, 154, 5,

 // slots: signature, parameters, type, tag, flags
       155, 175, 184, 185, 9,
       186, 202, 207, 208, 9,
       209, 225, 230, 231, 9,

 // properties: name, type, flags
       232, 239, 0x06005001, 		 // double Length
       246, 255, 0x06005003, 		 // double Position
       262, 267, 0x06005003, 		 // double Time
       274, 282, 0x0a055003, 		 // QString control
       290, 294, 0x06005001, 		 // double fps
       301, 309, 0x01005001, 		 // bool hasVout
       314, 319, 0x06005003, 		 // double rate
       326, 332, 0x02005001, 		 // int state

 // enums: name, flags, count, data
       336, 0x0, 7, 68, 

 // enum data: key, value
       352, AXVLC::VLCPlayListInsert,
       370, AXVLC::VLCPlayListInsertAndGo,
       393, AXVLC::VLCPlayListReplace,
       412, AXVLC::VLCPlayListReplaceAndGo,
       436, AXVLC::VLCPlayListAppend,
       454, AXVLC::VLCPlayListAppendAndGo,
       477, AXVLC::VLCPlayListCheckInsert,

        0        // eod
};

static const char *qt_meta_stringdata_AXVLC__IVLCInput() {
    static const char stringdata0[] = {
    "AXVLC::IVLCInput\0"
    "exception(int,QString,QString,QString)\0code,source,disc,help\0\0\0propertyChanged(QString)\0name\0\0\0signal(QString,int,void*)\0name,argc,argv\0\0\0"
    "SetPosition(double)\0Position\0\0\0SetTime(double)\0Time\0\0\0setRate(double)\0"
    "rate\0\0\0"
    "Length\0double\0Position\0double\0Time\0double\0control\0QString\0fps\0double\0hasVout\0bool\0rate\0double\0state\0int\0"
    };
    static char data[sizeof(stringdata0) + sizeof(qt_meta_enumstringdata_AXVLC)];
    if (!data[0]) {
        int index = 0;
        memcpy(data + index, stringdata0, sizeof(stringdata0) - 1);
        index += sizeof(stringdata0) - 1;
        memcpy(data + index, qt_meta_enumstringdata_AXVLC, sizeof(qt_meta_enumstringdata_AXVLC));
    }

    return data;
};

const QMetaObject IVLCInput::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_AXVLC__IVLCInput(),
qt_meta_data_AXVLC__IVLCInput }
};

void *IVLCInput::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, qt_meta_stringdata_AXVLC__IVLCInput()))
        return static_cast<void*>(const_cast<IVLCInput*>(this));
    return QAxObject::qt_metacast(_clname);
}

static const uint qt_meta_data_AXVLC__IVLCLog[] = {

 // content:
       1,       // revision
       0,       // classname
       0,    0, // classinfo
       4,    10, // methods
       3,    30, // properties
       1,    39, // enums/sets

 // signals: signature, parameters, type, tag, flags
       15, 54, 76, 77, 5,
       78, 103, 108, 109, 5,
       110, 136, 151, 152, 5,

 // slots: signature, parameters, type, tag, flags
       153, 171, 181, 182, 9,

 // properties: name, type, flags
       183, 191, 0x0a055003, 		 // QString control
       199, 208, 0x00005001, 		 // IVLCMessages* messages
       222, 232, 0x02005003, 		 // int verbosity

 // enums: name, flags, count, data
       236, 0x0, 7, 43, 

 // enum data: key, value
       252, AXVLC::VLCPlayListInsert,
       270, AXVLC::VLCPlayListInsertAndGo,
       293, AXVLC::VLCPlayListReplace,
       312, AXVLC::VLCPlayListReplaceAndGo,
       336, AXVLC::VLCPlayListAppend,
       354, AXVLC::VLCPlayListAppendAndGo,
       377, AXVLC::VLCPlayListCheckInsert,

        0        // eod
};

static const char *qt_meta_stringdata_AXVLC__IVLCLog() {
    static const char stringdata0[] = {
    "AXVLC::IVLCLog\0"
    "exception(int,QString,QString,QString)\0code,source,disc,help\0\0\0propertyChanged(QString)\0name\0\0\0signal(QString,int,void*)\0name,argc,argv\0\0\0"
    "setVerbosity(int)\0verbosity\0\0\0"
    "control\0QString\0messages\0IVLCMessages*\0"
    "verbosity\0int\0"
    };
    static char data[sizeof(stringdata0) + sizeof(qt_meta_enumstringdata_AXVLC)];
    if (!data[0]) {
        int index = 0;
        memcpy(data + index, stringdata0, sizeof(stringdata0) - 1);
        index += sizeof(stringdata0) - 1;
        memcpy(data + index, qt_meta_enumstringdata_AXVLC, sizeof(qt_meta_enumstringdata_AXVLC));
    }

    return data;
};

const QMetaObject IVLCLog::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_AXVLC__IVLCLog(),
qt_meta_data_AXVLC__IVLCLog }
};

void *IVLCLog::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, qt_meta_stringdata_AXVLC__IVLCLog()))
        return static_cast<void*>(const_cast<IVLCLog*>(this));
    return QAxObject::qt_metacast(_clname);
}

static const uint qt_meta_data_AXVLC__IVLCMessages[] = {

 // content:
       1,       // revision
       0,       // classname
       0,    0, // classinfo
       5,    10, // methods
       3,    35, // properties
       1,    44, // enums/sets

 // signals: signature, parameters, type, tag, flags
       20, 59, 81, 82, 5,
       83, 108, 113, 114, 5,
       115, 141, 156, 157, 5,

 // slots: signature, parameters, type, tag, flags
       158, 166, 167, 168, 9,
       169, 180, 181, 202, 9,

 // properties: name, type, flags
       203, 212, 0x00005001, 		 // IUnknown* _NewEnum
       222, 230, 0x0a055003, 		 // QString control
       238, 244, 0x02005001, 		 // int count

 // enums: name, flags, count, data
       248, 0x0, 7, 48, 

 // enum data: key, value
       264, AXVLC::VLCPlayListInsert,
       282, AXVLC::VLCPlayListInsertAndGo,
       305, AXVLC::VLCPlayListReplace,
       324, AXVLC::VLCPlayListReplaceAndGo,
       348, AXVLC::VLCPlayListAppend,
       366, AXVLC::VLCPlayListAppendAndGo,
       389, AXVLC::VLCPlayListCheckInsert,

        0        // eod
};

static const char *qt_meta_stringdata_AXVLC__IVLCMessages() {
    static const char stringdata0[] = {
    "AXVLC::IVLCMessages\0"
    "exception(int,QString,QString,QString)\0code,source,disc,help\0\0\0propertyChanged(QString)\0name\0\0\0signal(QString,int,void*)\0name,argc,argv\0\0\0"
    "clear()\0\0\0\0iterator()\0\0IVLCMessageIterator*\0\0"
    "_NewEnum\0IUnknown*\0"
    "control\0QString\0count\0int\0"
    };
    static char data[sizeof(stringdata0) + sizeof(qt_meta_enumstringdata_AXVLC)];
    if (!data[0]) {
        int index = 0;
        memcpy(data + index, stringdata0, sizeof(stringdata0) - 1);
        index += sizeof(stringdata0) - 1;
        memcpy(data + index, qt_meta_enumstringdata_AXVLC, sizeof(qt_meta_enumstringdata_AXVLC));
    }

    return data;
};

const QMetaObject IVLCMessages::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_AXVLC__IVLCMessages(),
qt_meta_data_AXVLC__IVLCMessages }
};

void *IVLCMessages::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, qt_meta_stringdata_AXVLC__IVLCMessages()))
        return static_cast<void*>(const_cast<IVLCMessages*>(this));
    return QAxObject::qt_metacast(_clname);
}

static const uint qt_meta_data_AXVLC__IVLCMessageIterator[] = {

 // content:
       1,       // revision
       0,       // classname
       0,    0, // classinfo
       4,    10, // methods
       2,    30, // properties
       1,    36, // enums/sets

 // signals: signature, parameters, type, tag, flags
       27, 66, 88, 89, 5,
       90, 115, 120, 121, 5,
       122, 148, 163, 164, 5,

 // slots: signature, parameters, type, tag, flags
       165, 172, 173, 186, 9,

 // properties: name, type, flags
       187, 195, 0x0a055003, 		 // QString control
       203, 211, 0x01005001, 		 // bool hasNext

 // enums: name, flags, count, data
       216, 0x0, 7, 40, 

 // enum data: key, value
       232, AXVLC::VLCPlayListInsert,
       250, AXVLC::VLCPlayListInsertAndGo,
       273, AXVLC::VLCPlayListReplace,
       292, AXVLC::VLCPlayListReplaceAndGo,
       316, AXVLC::VLCPlayListAppend,
       334, AXVLC::VLCPlayListAppendAndGo,
       357, AXVLC::VLCPlayListCheckInsert,

        0        // eod
};

static const char *qt_meta_stringdata_AXVLC__IVLCMessageIterator() {
    static const char stringdata0[] = {
    "AXVLC::IVLCMessageIterator\0"
    "exception(int,QString,QString,QString)\0code,source,disc,help\0\0\0propertyChanged(QString)\0name\0\0\0signal(QString,int,void*)\0name,argc,argv\0\0\0"
    "next()\0\0IVLCMessage*\0\0"
    "control\0QString\0hasNext\0bool\0"
    };
    static char data[sizeof(stringdata0) + sizeof(qt_meta_enumstringdata_AXVLC)];
    if (!data[0]) {
        int index = 0;
        memcpy(data + index, stringdata0, sizeof(stringdata0) - 1);
        index += sizeof(stringdata0) - 1;
        memcpy(data + index, qt_meta_enumstringdata_AXVLC, sizeof(qt_meta_enumstringdata_AXVLC));
    }

    return data;
};

const QMetaObject IVLCMessageIterator::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_AXVLC__IVLCMessageIterator(),
qt_meta_data_AXVLC__IVLCMessageIterator }
};

void *IVLCMessageIterator::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, qt_meta_stringdata_AXVLC__IVLCMessageIterator()))
        return static_cast<void*>(const_cast<IVLCMessageIterator*>(this));
    return QAxObject::qt_metacast(_clname);
}

static const uint qt_meta_data_AXVLC__IVLCMessage[] = {

 // content:
       1,       // revision
       0,       // classname
       0,    0, // classinfo
       3,    10, // methods
       7,    25, // properties
       1,    46, // enums/sets

 // signals: signature, parameters, type, tag, flags
       19, 58, 80, 81, 5,
       82, 107, 112, 113, 5,
       114, 140, 155, 156, 5,

 // slots: signature, parameters, type, tag, flags

 // properties: name, type, flags
       157, 164, 0xff005001, 		 // QVariant _Value
       173, 181, 0x0a055003, 		 // QString control
       189, 196, 0x0a005001, 		 // QString header
       204, 212, 0x0a005001, 		 // QString message
       220, 225, 0x0a005001, 		 // QString name
       233, 242, 0x02005001, 		 // int severity
       246, 251, 0x0a005001, 		 // QString type

 // enums: name, flags, count, data
       259, 0x0, 7, 50, 

 // enum data: key, value
       275, AXVLC::VLCPlayListInsert,
       293, AXVLC::VLCPlayListInsertAndGo,
       316, AXVLC::VLCPlayListReplace,
       335, AXVLC::VLCPlayListReplaceAndGo,
       359, AXVLC::VLCPlayListAppend,
       377, AXVLC::VLCPlayListAppendAndGo,
       400, AXVLC::VLCPlayListCheckInsert,

        0        // eod
};

static const char *qt_meta_stringdata_AXVLC__IVLCMessage() {
    static const char stringdata0[] = {
    "AXVLC::IVLCMessage\0"
    "exception(int,QString,QString,QString)\0code,source,disc,help\0\0\0propertyChanged(QString)\0name\0\0\0signal(QString,int,void*)\0name,argc,argv\0\0\0"
    ""
    "_Value\0QVariant\0control\0QString\0header\0QString\0message\0QString\0"
    "name\0QString\0severity\0int\0type\0QString\0"
    };
    static char data[sizeof(stringdata0) + sizeof(qt_meta_enumstringdata_AXVLC)];
    if (!data[0]) {
        int index = 0;
        memcpy(data + index, stringdata0, sizeof(stringdata0) - 1);
        index += sizeof(stringdata0) - 1;
        memcpy(data + index, qt_meta_enumstringdata_AXVLC, sizeof(qt_meta_enumstringdata_AXVLC));
    }

    return data;
};

const QMetaObject IVLCMessage::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_AXVLC__IVLCMessage(),
qt_meta_data_AXVLC__IVLCMessage }
};

void *IVLCMessage::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, qt_meta_stringdata_AXVLC__IVLCMessage()))
        return static_cast<void*>(const_cast<IVLCMessage*>(this));
    return QAxObject::qt_metacast(_clname);
}

static const uint qt_meta_data_AXVLC__IVLCPlaylist[] = {

 // content:
       1,       // revision
       0,       // classname
       0,    0, // classinfo
       14,    10, // methods
       4,    80, // properties
       1,    92, // enums/sets

 // signals: signature, parameters, type, tag, flags
       20, 59, 81, 82, 5,
       83, 108, 113, 114, 5,
       115, 141, 156, 157, 5,

 // slots: signature, parameters, type, tag, flags
       158, 171, 175, 179, 11,
       180, 202, 211, 215, 11,
       216, 247, 264, 268, 9,
       269, 277, 278, 279, 9,
       280, 287, 288, 289, 9,
       290, 297, 298, 299, 9,
       300, 314, 321, 322, 9,
       323, 330, 331, 332, 9,
       333, 349, 354, 355, 9,
       356, 363, 364, 365, 9,
       366, 380, 381, 382, 9,

 // properties: name, type, flags
       383, 391, 0x0a055003, 		 // QString control
       399, 409, 0x01005001, 		 // bool isPlaying
       414, 424, 0x02004001, 		 // int itemCount
       428, 434, 0x00005001, 		 // IVLCPlaylistItems* items

 // enums: name, flags, count, data
       453, 0x0, 7, 96, 

 // enum data: key, value
       469, AXVLC::VLCPlayListInsert,
       487, AXVLC::VLCPlayListInsertAndGo,
       510, AXVLC::VLCPlayListReplace,
       529, AXVLC::VLCPlayListReplaceAndGo,
       553, AXVLC::VLCPlayListAppend,
       571, AXVLC::VLCPlayListAppendAndGo,
       594, AXVLC::VLCPlayListCheckInsert,

        0        // eod
};

static const char *qt_meta_stringdata_AXVLC__IVLCPlaylist() {
    static const char stringdata0[] = {
    "AXVLC::IVLCPlaylist\0"
    "exception(int,QString,QString,QString)\0code,source,disc,help\0\0\0propertyChanged(QString)\0name\0\0\0signal(QString,int,void*)\0name,argc,argv\0\0\0"
    "add(QString)\0uri\0int\0\0add(QString,QVariant)\0uri,name\0int\0\0add(QString,QVariant,QVariant)\0"
    "uri,name,options\0int\0\0clear()\0\0\0\0next()\0\0\0\0play()\0\0\0\0playItem(int)\0itemId\0\0\0prev()\0\0\0\0removeItem(int)\0item\0\0\0stop()\0\0\0\0togglePause()\0\0\0\0"
    "control\0QString\0isPlaying\0bool\0itemCount\0int\0items\0IVLCPlaylistItems*\0"
    ""
    };
    static char data[sizeof(stringdata0) + sizeof(qt_meta_enumstringdata_AXVLC)];
    if (!data[0]) {
        int index = 0;
        memcpy(data + index, stringdata0, sizeof(stringdata0) - 1);
        index += sizeof(stringdata0) - 1;
        memcpy(data + index, qt_meta_enumstringdata_AXVLC, sizeof(qt_meta_enumstringdata_AXVLC));
    }

    return data;
};

const QMetaObject IVLCPlaylist::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_AXVLC__IVLCPlaylist(),
qt_meta_data_AXVLC__IVLCPlaylist }
};

void *IVLCPlaylist::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, qt_meta_stringdata_AXVLC__IVLCPlaylist()))
        return static_cast<void*>(const_cast<IVLCPlaylist*>(this));
    return QAxObject::qt_metacast(_clname);
}

static const uint qt_meta_data_AXVLC__IVLCPlaylistItems[] = {

 // content:
       1,       // revision
       0,       // classname
       0,    0, // classinfo
       5,    10, // methods
       2,    35, // properties
       1,    41, // enums/sets

 // signals: signature, parameters, type, tag, flags
       25, 64, 86, 87, 5,
       88, 113, 118, 119, 5,
       120, 146, 161, 162, 5,

 // slots: signature, parameters, type, tag, flags
       163, 171, 172, 173, 9,
       174, 186, 193, 194, 9,

 // properties: name, type, flags
       195, 203, 0x0a055003, 		 // QString control
       211, 217, 0x02005001, 		 // int count

 // enums: name, flags, count, data
       221, 0x0, 7, 45, 

 // enum data: key, value
       237, AXVLC::VLCPlayListInsert,
       255, AXVLC::VLCPlayListInsertAndGo,
       278, AXVLC::VLCPlayListReplace,
       297, AXVLC::VLCPlayListReplaceAndGo,
       321, AXVLC::VLCPlayListAppend,
       339, AXVLC::VLCPlayListAppendAndGo,
       362, AXVLC::VLCPlayListCheckInsert,

        0        // eod
};

static const char *qt_meta_stringdata_AXVLC__IVLCPlaylistItems() {
    static const char stringdata0[] = {
    "AXVLC::IVLCPlaylistItems\0"
    "exception(int,QString,QString,QString)\0code,source,disc,help\0\0\0propertyChanged(QString)\0name\0\0\0signal(QString,int,void*)\0name,argc,argv\0\0\0"
    "clear()\0\0\0\0remove(int)\0itemId\0\0\0"
    "control\0QString\0count\0int\0"
    };
    static char data[sizeof(stringdata0) + sizeof(qt_meta_enumstringdata_AXVLC)];
    if (!data[0]) {
        int index = 0;
        memcpy(data + index, stringdata0, sizeof(stringdata0) - 1);
        index += sizeof(stringdata0) - 1;
        memcpy(data + index, qt_meta_enumstringdata_AXVLC, sizeof(qt_meta_enumstringdata_AXVLC));
    }

    return data;
};

const QMetaObject IVLCPlaylistItems::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_AXVLC__IVLCPlaylistItems(),
qt_meta_data_AXVLC__IVLCPlaylistItems }
};

void *IVLCPlaylistItems::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, qt_meta_stringdata_AXVLC__IVLCPlaylistItems()))
        return static_cast<void*>(const_cast<IVLCPlaylistItems*>(this));
    return QAxObject::qt_metacast(_clname);
}

static const uint qt_meta_data_AXVLC__IVLCVideo[] = {

 // content:
       1,       // revision
       0,       // classname
       0,    0, // classinfo
       11,    10, // methods
       8,    65, // properties
       1,    89, // enums/sets

 // signals: signature, parameters, type, tag, flags
       17, 56, 78, 79, 5,
       80, 105, 110, 111, 5,
       112, 138, 153, 154, 5,

 // slots: signature, parameters, type, tag, flags
       155, 179, 191, 192, 9,
       193, 210, 215, 216, 9,
       217, 237, 248, 249, 9,
       250, 267, 276, 277, 9,
       278, 295, 304, 305, 9,
       306, 321, 322, 330, 9,
       331, 350, 351, 352, 9,
       353, 370, 371, 372, 9,

 // properties: name, type, flags
       373, 385, 0x0a005003, 		 // QString aspectRatio
       393, 401, 0x0a055003, 		 // QString control
       409, 414, 0x0a005003, 		 // QString crop
       422, 433, 0x01005003, 		 // bool fullscreen
       438, 445, 0x02005001, 		 // int height
       449, 458, 0x02005003, 		 // int subtitle
       462, 471, 0x02005003, 		 // int teletext
       475, 481, 0x02005001, 		 // int width

 // enums: name, flags, count, data
       485, 0x0, 7, 93, 

 // enum data: key, value
       501, AXVLC::VLCPlayListInsert,
       519, AXVLC::VLCPlayListInsertAndGo,
       542, AXVLC::VLCPlayListReplace,
       561, AXVLC::VLCPlayListReplaceAndGo,
       585, AXVLC::VLCPlayListAppend,
       603, AXVLC::VLCPlayListAppendAndGo,
       626, AXVLC::VLCPlayListCheckInsert,

        0        // eod
};

static const char *qt_meta_stringdata_AXVLC__IVLCVideo() {
    static const char stringdata0[] = {
    "AXVLC::IVLCVideo\0"
    "exception(int,QString,QString,QString)\0code,source,disc,help\0\0\0propertyChanged(QString)\0name\0\0\0signal(QString,int,void*)\0name,argc,argv\0\0\0"
    "setAspectRatio(QString)\0aspectRatio\0\0\0setCrop(QString)\0crop\0\0\0setFullscreen(bool)\0"
    "fullscreen\0\0\0setSubtitle(int)\0subtitle\0\0\0setTeletext(int)\0teletext\0\0\0takeSnapshot()\0\0QPixmap\0\0toggleFullscreen()\0\0\0\0toggleTeletext()\0\0\0\0"
    "aspectRatio\0QString\0control\0QString\0crop\0QString\0fullscreen\0bool\0"
    "height\0int\0subtitle\0int\0teletext\0int\0width\0int\0"
    };
    static char data[sizeof(stringdata0) + sizeof(qt_meta_enumstringdata_AXVLC)];
    if (!data[0]) {
        int index = 0;
        memcpy(data + index, stringdata0, sizeof(stringdata0) - 1);
        index += sizeof(stringdata0) - 1;
        memcpy(data + index, qt_meta_enumstringdata_AXVLC, sizeof(qt_meta_enumstringdata_AXVLC));
    }

    return data;
};

const QMetaObject IVLCVideo::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_AXVLC__IVLCVideo(),
qt_meta_data_AXVLC__IVLCVideo }
};

void *IVLCVideo::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, qt_meta_stringdata_AXVLC__IVLCVideo()))
        return static_cast<void*>(const_cast<IVLCVideo*>(this));
    return QAxObject::qt_metacast(_clname);
}

static const uint qt_meta_data_AXVLC__IVLCControl2[] = {

 // content:
       1,       // revision
       0,       // classname
       0,    0, // classinfo
       12,    10, // methods
       16,    70, // properties
       1,    118, // enums/sets

 // signals: signature, parameters, type, tag, flags
       20, 59, 81, 82, 5,
       83, 108, 113, 114, 5,
       115, 141, 156, 157, 5,

 // slots: signature, parameters, type, tag, flags
       158, 176, 185, 186, 9,
       187, 205, 214, 215, 9,
       216, 237, 247, 248, 9,
       249, 269, 277, 278, 9,
       279, 295, 299, 300, 9,
       301, 319, 329, 330, 9,
       331, 348, 356, 357, 9,
       358, 375, 383, 384, 9,
       385, 400, 407, 408, 9,

 // properties: name, type, flags
       409, 418, 0x01005003, 		 // bool AutoLoop
       423, 432, 0x01005003, 		 // bool AutoPlay
       437, 447, 0x43005003, 		 // QColor BackColor
       454, 462, 0x0a005003, 		 // QString BaseURL
       470, 474, 0x0a005003, 		 // QString MRL
       482, 492, 0x02005003, 		 // int StartTime
       496, 504, 0x01005003, 		 // bool Toolbar
       509, 521, 0x0a005001, 		 // QString VersionInfo
       529, 537, 0x01005003, 		 // bool Visible
       542, 549, 0x02005003, 		 // int Volume
       553, 559, 0x00005001, 		 // IVLCAudio* audio
       570, 578, 0x0a055003, 		 // QString control
       586, 592, 0x00005001, 		 // IVLCInput* input
       603, 607, 0x00005001, 		 // IVLCLog* log
       616, 625, 0x00005001, 		 // IVLCPlaylist* playlist
       639, 645, 0x00005001, 		 // IVLCVideo* video

 // enums: name, flags, count, data
       656, 0x0, 7, 122, 

 // enum data: key, value
       672, AXVLC::VLCPlayListInsert,
       690, AXVLC::VLCPlayListInsertAndGo,
       713, AXVLC::VLCPlayListReplace,
       732, AXVLC::VLCPlayListReplaceAndGo,
       756, AXVLC::VLCPlayListAppend,
       774, AXVLC::VLCPlayListAppendAndGo,
       797, AXVLC::VLCPlayListCheckInsert,

        0        // eod
};

static const char *qt_meta_stringdata_AXVLC__IVLCControl2() {
    static const char stringdata0[] = {
    "AXVLC::IVLCControl2\0"
    "exception(int,QString,QString,QString)\0code,source,disc,help\0\0\0propertyChanged(QString)\0name\0\0\0signal(QString,int,void*)\0name,argc,argv\0\0\0"
    "SetAutoLoop(bool)\0AutoLoop\0\0\0SetAutoPlay(bool)\0AutoPlay\0\0\0SetBackColor(QColor)\0"
    "BackColor\0\0\0SetBaseURL(QString)\0BaseURL\0\0\0SetMRL(QString)\0MRL\0\0\0SetStartTime(int)\0StartTime\0\0\0SetToolbar(bool)\0Toolbar\0\0\0SetVisible(bool)\0Visible\0\0\0SetVolume(int)\0Volume\0\0\0"
    "AutoLoop\0bool\0AutoPlay\0bool\0BackColor\0"
    "QColor\0BaseURL\0QString\0MRL\0QString\0StartTime\0int\0Toolbar\0bool\0VersionInfo\0QString\0Visible\0bool\0Volume\0int\0audio\0IVLCAudio*\0control\0QString\0input\0IVLCInput*\0log\0IVLCLog*\0playlist\0IVLCPlaylist*\0video\0IVLCVideo*\0"
    ""
    };
    static char data[sizeof(stringdata0) + sizeof(qt_meta_enumstringdata_AXVLC)];
    if (!data[0]) {
        int index = 0;
        memcpy(data + index, stringdata0, sizeof(stringdata0) - 1);
        index += sizeof(stringdata0) - 1;
        memcpy(data + index, qt_meta_enumstringdata_AXVLC, sizeof(qt_meta_enumstringdata_AXVLC));
    }

    return data;
};

const QMetaObject IVLCControl2::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_AXVLC__IVLCControl2(),
qt_meta_data_AXVLC__IVLCControl2 }
};

void *IVLCControl2::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, qt_meta_stringdata_AXVLC__IVLCControl2()))
        return static_cast<void*>(const_cast<IVLCControl2*>(this));
    return QAxObject::qt_metacast(_clname);
}

static const uint qt_meta_data_AXVLC__VLCPlugin[] = {

 // content:
       1,       // revision
       0,       // classname
       3,    10, // classinfo
       31,    16, // methods
       21,    171, // properties
       1,    234, // enums/sets

 // classinfo: key, value
       17, 35, 
       46, 58, 
       70, 82, 

 // signals: signature, parameters, type, tag, flags
       95, 116, 124, 125, 5,
       126, 165, 187, 188, 5,
       189, 197, 198, 199, 5,
       200, 207, 208, 209, 5,
       210, 235, 240, 241, 5,
       242, 249, 250, 251, 5,

 // slots: signature, parameters, type, tag, flags
       252, 270, 279, 280, 9,
       281, 299, 308, 309, 9,
       310, 331, 341, 342, 9,
       343, 363, 371, 372, 9,
       373, 389, 393, 394, 9,
       395, 415, 424, 425, 9,
       426, 444, 454, 455, 9,
       456, 469, 474, 475, 9,
       476, 493, 501, 502, 9,
       503, 520, 528, 529, 9,
       530, 545, 552, 553, 9,
       554, 602, 628, 629, 9,
       630, 643, 644, 645, 9,
       646, 667, 672, 681, 9,
       682, 690, 691, 692, 9,
       693, 700, 701, 702, 9,
       703, 716, 717, 718, 9,
       719, 732, 733, 734, 9,
       735, 751, 752, 753, 9,
       754, 769, 770, 771, 9,
       772, 787, 788, 789, 9,
       790, 820, 831, 832, 9,
       833, 846, 854, 855, 9,
       856, 863, 864, 865, 9,
       866, 879, 880, 881, 9,

 // properties: name, type, flags
       882, 891, 0x01005003, 		 // bool AutoLoop
       896, 905, 0x01005003, 		 // bool AutoPlay
       910, 920, 0x43005003, 		 // QColor BackColor
       927, 935, 0x0a005003, 		 // QString BaseURL
       943, 950, 0x02004001, 		 // int Length
       954, 958, 0x0a005003, 		 // QString MRL
       966, 974, 0x01004001, 		 // bool Playing
       979, 993, 0x02005001, 		 // int PlaylistCount
       997, 1011, 0x02005001, 		 // int PlaylistIndex
       1015, 1024, 0x06005003, 		 // double Position
       1031, 1041, 0x02005003, 		 // int StartTime
       1045, 1050, 0x02005003, 		 // int Time
       1054, 1062, 0x01005003, 		 // bool Toolbar
       1067, 1079, 0x0a005001, 		 // QString VersionInfo
       1087, 1095, 0x01005003, 		 // bool Visible
       1100, 1107, 0x02005003, 		 // int Volume
       1111, 1117, 0x00005001, 		 // IVLCAudio* audio
       1128, 1134, 0x00005001, 		 // IVLCInput* input
       1145, 1149, 0x00005001, 		 // IVLCLog* log
       1158, 1167, 0x00005001, 		 // IVLCPlaylist* playlist
       1181, 1187, 0x00005001, 		 // IVLCVideo* video

 // enums: name, flags, count, data
       1198, 0x0, 7, 238, 

 // enum data: key, value
       1214, AXVLC::VLCPlayListInsert,
       1232, AXVLC::VLCPlayListInsertAndGo,
       1255, AXVLC::VLCPlayListReplace,
       1274, AXVLC::VLCPlayListReplaceAndGo,
       1298, AXVLC::VLCPlayListAppend,
       1316, AXVLC::VLCPlayListAppendAndGo,
       1339, AXVLC::VLCPlayListCheckInsert,

        0        // eod
};

static const char *qt_meta_stringdata_AXVLC__VLCPlugin() {
    static const char stringdata0[] = {
    "AXVLC::VLCPlugin\0"
    "Event Interface 2\0DVLCEvents\0Interface 0\0IVLCControl\0Interface 1\0IVLCControl2\0"
    "VisibleChanged(bool)\0Visible\0\0\0exception(int,QString,QString,QString)\0code,source,disc,help\0\0\0pause()\0\0\0\0play()\0\0\0\0propertyChanged(QString)\0"
    "name\0\0\0stop()\0\0\0\0"
    "SetAutoLoop(bool)\0AutoLoop\0\0\0SetAutoPlay(bool)\0AutoPlay\0\0\0SetBackColor(QColor)\0BackColor\0\0\0SetBaseURL(QString)\0BaseURL\0\0\0SetMRL(QString)\0MRL\0\0\0SetPosition(double)\0Position\0\0\0SetStartTime(int)\0"
    "StartTime\0\0\0SetTime(int)\0Time\0\0\0SetToolbar(bool)\0Toolbar\0\0\0SetVisible(bool)\0Visible\0\0\0SetVolume(int)\0Volume\0\0\0addTarget(QString,QVariant,VLCPlaylistMode,int)\0uri,options,mode,Position\0\0\0fullscreen()\0\0\0"
    "\0getVariable(QString)\0name\0QVariant\0\0pause()\0\0\0\0play()\0\0\0\0playFaster()\0\0\0\0playSlower()\0\0\0\0playlistClear()\0\0\0\0playlistNext()\0\0\0\0playlistPrev()\0\0\0\0setVariable(QString,QVariant)\0name,value\0\0\0shuttle(int)\0"
    "seconds\0\0\0stop()\0\0\0\0toggleMute()\0\0\0\0"
    "AutoLoop\0bool\0AutoPlay\0bool\0BackColor\0QColor\0BaseURL\0QString\0Length\0int\0MRL\0QString\0Playing\0bool\0PlaylistCount\0int\0PlaylistIndex\0int\0Position\0double\0StartTime\0int\0Time\0"
    "int\0Toolbar\0bool\0VersionInfo\0QString\0Visible\0bool\0Volume\0int\0audio\0IVLCAudio*\0input\0IVLCInput*\0log\0IVLCLog*\0playlist\0IVLCPlaylist*\0video\0IVLCVideo*\0"
    };
    static char data[sizeof(stringdata0) + sizeof(qt_meta_enumstringdata_AXVLC)];
    if (!data[0]) {
        int index = 0;
        memcpy(data + index, stringdata0, sizeof(stringdata0) - 1);
        index += sizeof(stringdata0) - 1;
        memcpy(data + index, qt_meta_enumstringdata_AXVLC, sizeof(qt_meta_enumstringdata_AXVLC));
    }

    return data;
};

const QMetaObject VLCPlugin::staticMetaObject = {
{ &QWidget::staticMetaObject,
qt_meta_stringdata_AXVLC__VLCPlugin(),
qt_meta_data_AXVLC__VLCPlugin }
};

void *VLCPlugin::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, qt_meta_stringdata_AXVLC__VLCPlugin()))
        return static_cast<void*>(const_cast<VLCPlugin*>(this));
    return QAxWidget::qt_metacast(_clname);
}

static const uint qt_meta_data_AXVLC__VLCPlugin2[] = {

 // content:
       1,       // revision
       0,       // classname
       2,    10, // classinfo
       28,    14, // methods
       21,    154, // properties
       1,    217, // enums/sets

 // classinfo: key, value
       18, 30, 
       43, 55, 

 // signals: signature, parameters, type, tag, flags
       67, 88, 96, 97, 5,
       98, 137, 159, 160, 5,
       161, 186, 191, 192, 5,

 // slots: signature, parameters, type, tag, flags
       193, 211, 220, 221, 9,
       222, 240, 249, 250, 9,
       251, 272, 282, 283, 9,
       284, 304, 312, 313, 9,
       314, 330, 334, 335, 9,
       336, 356, 365, 366, 9,
       367, 385, 395, 396, 9,
       397, 410, 415, 416, 9,
       417, 434, 442, 443, 9,
       444, 461, 469, 470, 9,
       471, 486, 493, 494, 9,
       495, 543, 569, 570, 9,
       571, 584, 585, 586, 9,
       587, 608, 613, 622, 9,
       623, 631, 632, 633, 9,
       634, 641, 642, 643, 9,
       644, 657, 658, 659, 9,
       660, 673, 674, 675, 9,
       676, 692, 693, 694, 9,
       695, 710, 711, 712, 9,
       713, 728, 729, 730, 9,
       731, 761, 772, 773, 9,
       774, 787, 795, 796, 9,
       797, 804, 805, 806, 9,
       807, 820, 821, 822, 9,

 // properties: name, type, flags
       823, 832, 0x01005003, 		 // bool AutoLoop
       837, 846, 0x01005003, 		 // bool AutoPlay
       851, 861, 0x43005003, 		 // QColor BackColor
       868, 876, 0x0a005003, 		 // QString BaseURL
       884, 891, 0x02004001, 		 // int Length
       895, 899, 0x0a005003, 		 // QString MRL
       907, 915, 0x01004001, 		 // bool Playing
       920, 934, 0x02005001, 		 // int PlaylistCount
       938, 952, 0x02005001, 		 // int PlaylistIndex
       956, 965, 0x06005003, 		 // double Position
       972, 982, 0x02005003, 		 // int StartTime
       986, 991, 0x02005003, 		 // int Time
       995, 1003, 0x01005003, 		 // bool Toolbar
       1008, 1020, 0x0a005001, 		 // QString VersionInfo
       1028, 1036, 0x01005003, 		 // bool Visible
       1041, 1048, 0x02005003, 		 // int Volume
       1052, 1058, 0x00005001, 		 // IVLCAudio* audio
       1069, 1075, 0x00005001, 		 // IVLCInput* input
       1086, 1090, 0x00005001, 		 // IVLCLog* log
       1099, 1108, 0x00005001, 		 // IVLCPlaylist* playlist
       1122, 1128, 0x00005001, 		 // IVLCVideo* video

 // enums: name, flags, count, data
       1139, 0x0, 7, 221, 

 // enum data: key, value
       1155, AXVLC::VLCPlayListInsert,
       1173, AXVLC::VLCPlayListInsertAndGo,
       1196, AXVLC::VLCPlayListReplace,
       1215, AXVLC::VLCPlayListReplaceAndGo,
       1239, AXVLC::VLCPlayListAppend,
       1257, AXVLC::VLCPlayListAppendAndGo,
       1280, AXVLC::VLCPlayListCheckInsert,

        0        // eod
};

static const char *qt_meta_stringdata_AXVLC__VLCPlugin2() {
    static const char stringdata0[] = {
    "AXVLC::VLCPlugin2\0"
    "Interface 0\0IVLCControl2\0Interface 1\0IVLCControl\0"
    "VisibleChanged(bool)\0Visible\0\0\0exception(int,QString,QString,QString)\0code,source,disc,help\0\0\0propertyChanged(QString)\0name\0\0\0"
    "SetAutoLoop(bool)\0AutoLoop\0"
    "\0\0SetAutoPlay(bool)\0AutoPlay\0\0\0SetBackColor(QColor)\0BackColor\0\0\0SetBaseURL(QString)\0BaseURL\0\0\0SetMRL(QString)\0MRL\0\0\0SetPosition(double)\0Position\0\0\0SetStartTime(int)\0StartTime\0\0\0SetTime(int)\0Time\0\0\0SetToolbar(bool)\0"
    "Toolbar\0\0\0SetVisible(bool)\0Visible\0\0\0SetVolume(int)\0Volume\0\0\0addTarget(QString,QVariant,VLCPlaylistMode,int)\0uri,options,mode,Position\0\0\0fullscreen()\0\0\0\0getVariable(QString)\0name\0QVariant\0\0pause()\0\0\0\0play()\0"
    "\0\0\0playFaster()\0\0\0\0playSlower()\0\0\0\0playlistClear()\0\0\0\0playlistNext()\0\0\0\0playlistPrev()\0\0\0\0setVariable(QString,QVariant)\0name,value\0\0\0shuttle(int)\0seconds\0\0\0stop()\0\0\0\0toggleMute()\0\0\0\0"
    "AutoLoop\0bool\0AutoPlay\0"
    "bool\0BackColor\0QColor\0BaseURL\0QString\0Length\0int\0MRL\0QString\0Playing\0bool\0PlaylistCount\0int\0PlaylistIndex\0int\0Position\0double\0StartTime\0int\0Time\0int\0Toolbar\0bool\0VersionInfo\0QString\0Visible\0bool\0Volume\0"
    "int\0audio\0IVLCAudio*\0input\0IVLCInput*\0log\0IVLCLog*\0playlist\0IVLCPlaylist*\0video\0IVLCVideo*\0"
    };
    static char data[sizeof(stringdata0) + sizeof(qt_meta_enumstringdata_AXVLC)];
    if (!data[0]) {
        int index = 0;
        memcpy(data + index, stringdata0, sizeof(stringdata0) - 1);
        index += sizeof(stringdata0) - 1;
        memcpy(data + index, qt_meta_enumstringdata_AXVLC, sizeof(qt_meta_enumstringdata_AXVLC));
    }

    return data;
};

const QMetaObject VLCPlugin2::staticMetaObject = {
{ &QWidget::staticMetaObject,
qt_meta_stringdata_AXVLC__VLCPlugin2(),
qt_meta_data_AXVLC__VLCPlugin2 }
};

void *VLCPlugin2::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, qt_meta_stringdata_AXVLC__VLCPlugin2()))
        return static_cast<void*>(const_cast<VLCPlugin2*>(this));
    return QAxWidget::qt_metacast(_clname);
}

