/****************************************************************************
**
** Namespace AXVLC generated by dumpcpp from type library
** C:\Programme\VideoLAN\VLC\axvlc.dll
**
****************************************************************************/

#ifndef QAX_DUMPCPP_AXVLC_H
#define QAX_DUMPCPP_AXVLC_H

// Define this symbol to __declspec(dllexport) or __declspec(dllimport)
#ifndef AXVLC_EXPORT
#define AXVLC_EXPORT
#endif

#include <qaxobject.h>
#include <qaxwidget.h>
#include <qdatetime.h>
#include <qpixmap.h>

struct IDispatch;


// Referenced namespace

namespace AXVLC {

    enum VLCPlaylistMode {
        VLCPlayListInsert       = 1,
        VLCPlayListInsertAndGo  = 9,
        VLCPlayListReplace      = 2,
        VLCPlayListReplaceAndGo = 10,
        VLCPlayListAppend       = 4,
        VLCPlayListAppendAndGo  = 12,
        VLCPlayListCheckInsert  = 16
    };

// forward declarations
    enum VLCPlaylistMode;
    enum VLCPlaylistMode;
    class IVLCMessages;
    class IVLCMessageIterator;
    class IVLCMessage;
    class IVLCPlaylistItems;
    class IVLCAudio;
    class IVLCInput;
    class IVLCLog;
    class IVLCPlaylist;
    class IVLCVideo;

class AXVLC_EXPORT IVLCControl : public QAxObject
{
public:
    IVLCControl(IDispatch *subobject = 0, QAxObject *parent = 0)
    : QAxObject((IUnknown*)subobject, parent)
    {
        internalRelease();
    }

    /*
    Property AutoLoop

    Returns/sets a value that determines whether the playlist is looped

    */
    inline bool AutoLoop() const; //Returns the value of AutoLoop
    inline void SetAutoLoop(bool value); //Sets the value of the AutoLoop property

    /*
    Property AutoPlay

    Returns/sets a value that determines whether the playlist is played on startup

    */
    inline bool AutoPlay() const; //Returns the value of AutoPlay
    inline void SetAutoPlay(bool value); //Sets the value of the AutoPlay property

    /*
    Property Length

    Returns the total length, in seconds, of the current item, may be unknown.

    */
    inline int Length() const; //Returns the value of Length

    /*
    Property MRL

    Returns/sets the first MRL in playlist, used for AutoPlay

    */
    inline QString MRL() const; //Returns the value of MRL
    inline void SetMRL(const QString& value); //Sets the value of the MRL property

    /*
    Property Playing

    Returns a value that determines whether VLC is currently playing.

    */
    inline bool Playing() const; //Returns the value of Playing

    /*
    Property PlaylistCount

    Returns number of items in playlist.

    */
    inline int PlaylistCount() const; //Returns the value of PlaylistCount

    /*
    Property PlaylistIndex

    Returns index of current item in playlist.

    */
    inline int PlaylistIndex() const; //Returns the value of PlaylistIndex

    /*
    Property Position

    Returns/sets playback position within the current item. Position is a relative value ranging from 0.0 to 1.0.

    */
    inline double Position() const; //Returns the value of Position
    inline void SetPosition(double value); //Sets the value of the Position property

    /*
    Property Time

    Returns/sets playback time relative to the start of the current item.

    */
    inline int Time() const; //Returns the value of Time
    inline void SetTime(int value); //Sets the value of the Time property

    /*
    Property VersionInfo

    Returns VLC Version.

    */
    inline QString VersionInfo() const; //Returns the value of VersionInfo

    /*
    Property Visible

    Returns/sets a value that determines whether viewing area is visible or hidden.

    */
    inline bool Visible() const; //Returns the value of Visible
    inline void SetVisible(bool value); //Sets the value of the Visible property

    /*
    Property Volume

    Returns/sets playback volume, ranges from 0 to 200%.

    */
    inline int Volume() const; //Returns the value of Volume
    inline void SetVolume(int value); //Sets the value of the Volume property

    /*
    Method addTarget

    Add an item to the playlist.

    */
    inline void addTarget(const QString& uri, const QVariant& options, AXVLC::VLCPlaylistMode mode, int Position);

    /*
    Method fullscreen

    Switch video between normal and fullscreen view modes.

    */
    inline void fullscreen();

    /*
    Method getVariable

    Returns the value of a VLC variable.

    */
    inline QVariant getVariable(const QString& name);

    /*
    Method pause

    Pause playback.

    */
    inline void pause();

    /*
    Method play

    Play current target in playlist.

    */
    inline void play();

    /*
    Method playFaster

    Increases playback speed. Possible speeds are: 1x, 2x, 4x, 8x.

    */
    inline void playFaster();

    /*
    Method playSlower

    Decreases playback speed. Possible speeds are: 1x, 2x, 4x, 8x.

    */
    inline void playSlower();

    /*
    Method playlistClear

    Remove all items from playlist.

    */
    inline void playlistClear();

    /*
    Method playlistNext

    Advance to next item in playlist.

    */
    inline void playlistNext();

    /*
    Method playlistPrev

    Advance to previous item in playlist.

    */
    inline void playlistPrev();

    /*
    Method setVariable

    Sets the value of a VLC variable.

    */
    inline void setVariable(const QString& name, const QVariant& value);

    /*
    Method shuttle

    Advance or backtrack playback time, relative to current time.

    */
    inline void shuttle(int seconds);

    /*
    Method stop

    Stop playback.

    */
    inline void stop();

    /*
    Method toggleMute

    Mute/unmute playback audio.

    */
    inline void toggleMute();

// meta object functions
    static const QMetaObject staticMetaObject;
    virtual const QMetaObject *metaObject() const { return &staticMetaObject; }
    virtual void *qt_metacast(const char *);
};

class AXVLC_EXPORT IVLCAudio : public QAxObject
{
public:
    IVLCAudio(IDispatch *subobject = 0, QAxObject *parent = 0)
    : QAxObject((IUnknown*)subobject, parent)
    {
        internalRelease();
    }

    /*
    Property Volume

    Returns/sets audio volume as a percent value.

    */
    inline int Volume() const; //Returns the value of Volume
    inline void SetVolume(int value); //Sets the value of the Volume property

    /*
    Property channel

    Returns audio channel [1-5] indicating; stereo, reverse stereo, left, right, dolby.

    */
    inline int channel() const; //Returns the value of channel
    inline void setChannel(int value); //Sets the value of the channel property

    /*
    Property mute

    Returns/sets the audio mute state.

    */
    inline bool mute() const; //Returns the value of mute
    inline void setMute(bool value); //Sets the value of the mute property

    /*
    Property track

    Returns/sets audio track used/to use.

    */
    inline int track() const; //Returns the value of track
    inline void setTrack(int value); //Sets the value of the track property

    /*
    Method toggleMute

    Mute/unmute audio playback.

    */
    inline void toggleMute();

// meta object functions
    static const QMetaObject staticMetaObject;
    virtual const QMetaObject *metaObject() const { return &staticMetaObject; }
    virtual void *qt_metacast(const char *);
};

class AXVLC_EXPORT IVLCInput : public QAxObject
{
public:
    IVLCInput(IDispatch *subobject = 0, QAxObject *parent = 0)
    : QAxObject((IUnknown*)subobject, parent)
    {
        internalRelease();
    }

    /*
    Property Length

    Returns the clip length, in milliseconds.

    */
    inline double Length() const; //Returns the value of Length

    /*
    Property Position

    Returns/sets playback position in current clip.  Position is ranging from 0.0 to 1.0.

    */
    inline double Position() const; //Returns the value of Position
    inline void SetPosition(double value); //Sets the value of the Position property

    /*
    Property Time

    Returns/sets playback time in current clip, in milliseconds.

    */
    inline double Time() const; //Returns the value of Time
    inline void SetTime(double value); //Sets the value of the Time property

    /*
    Property fps

    Returns current playback frames per seconds if available.

    */
    inline double fps() const; //Returns the value of fps

    /*
    Property hasVout

    Returns whether current playback displays video.

    */
    inline bool hasVout() const; //Returns the value of hasVout

    /*
    Property rate

    Returns/sets current playback rate, normal rate is 1.0 

    */
    inline double rate() const; //Returns the value of rate
    inline void setRate(double value); //Sets the value of the rate property

    /*
    Property state

    Returns current playback state.

    */
    inline int state() const; //Returns the value of state

// meta object functions
    static const QMetaObject staticMetaObject;
    virtual const QMetaObject *metaObject() const { return &staticMetaObject; }
    virtual void *qt_metacast(const char *);
};

class AXVLC_EXPORT IVLCLog : public QAxObject
{
public:
    IVLCLog(IDispatch *subobject = 0, QAxObject *parent = 0)
    : QAxObject((IUnknown*)subobject, parent)
    {
        internalRelease();
    }

    /*
    Property messages

    Returns messages in log

    */
    inline AXVLC::IVLCMessages* messages() const; //Returns the value of messages

    /*
    Property verbosity

    Returns/Sets the log versbosity level.

    */
    inline int verbosity() const; //Returns the value of verbosity
    inline void setVerbosity(int value); //Sets the value of the verbosity property

// meta object functions
    static const QMetaObject staticMetaObject;
    virtual const QMetaObject *metaObject() const { return &staticMetaObject; }
    virtual void *qt_metacast(const char *);
};

class AXVLC_EXPORT IVLCMessages : public QAxObject
{
public:
    IVLCMessages(IDispatch *subobject = 0, QAxObject *parent = 0)
    : QAxObject((IUnknown*)subobject, parent)
    {
        internalRelease();
    }

    /*
    Property _NewEnum
    */
    inline IUnknown* _NewEnum() const; //Returns the value of _NewEnum

    /*
    Property count

    Returns the number of messages.

    */
    inline int count() const; //Returns the value of count

    /*
    Method clear

    Clear all messages from log.

    */
    inline void clear();

    /*
    Method iterator

    Returns an iterator for messages in log

    */
    inline AXVLC::IVLCMessageIterator* iterator();

// meta object functions
    static const QMetaObject staticMetaObject;
    virtual const QMetaObject *metaObject() const { return &staticMetaObject; }
    virtual void *qt_metacast(const char *);
};

class AXVLC_EXPORT IVLCMessageIterator : public QAxObject
{
public:
    IVLCMessageIterator(IDispatch *subobject = 0, QAxObject *parent = 0)
    : QAxObject((IUnknown*)subobject, parent)
    {
        internalRelease();
    }

    /*
    Property hasNext

    Returns whether a message is available.

    */
    inline bool hasNext() const; //Returns the value of hasNext

    /*
    Method next

    Returns next message.

    */
    inline AXVLC::IVLCMessage* next();

// meta object functions
    static const QMetaObject staticMetaObject;
    virtual const QMetaObject *metaObject() const { return &staticMetaObject; }
    virtual void *qt_metacast(const char *);
};

class AXVLC_EXPORT IVLCMessage : public QAxObject
{
public:
    IVLCMessage(IDispatch *subobject = 0, QAxObject *parent = 0)
    : QAxObject((IUnknown*)subobject, parent)
    {
        internalRelease();
    }

    /*
    Property _Value
    */
    inline QVariant _Value() const; //Returns the value of _Value

    /*
    Property header

    Returns message header.

    */
    inline QString header() const; //Returns the value of header

    /*
    Property message

    Returns message content.

    */
    inline QString message() const; //Returns the value of message

    /*
    Property name

    Returns message issuer name.

    */
    inline QString name() const; //Returns the value of name

    /*
    Property severity

    Returns message severity.

    */
    inline int severity() const; //Returns the value of severity

    /*
    Property type

    Returns message issuer type.

    */
    inline QString type() const; //Returns the value of type

// meta object functions
    static const QMetaObject staticMetaObject;
    virtual const QMetaObject *metaObject() const { return &staticMetaObject; }
    virtual void *qt_metacast(const char *);
};

class AXVLC_EXPORT IVLCPlaylist : public QAxObject
{
public:
    IVLCPlaylist(IDispatch *subobject = 0, QAxObject *parent = 0)
    : QAxObject((IUnknown*)subobject, parent)
    {
        internalRelease();
    }

    /*
    Property isPlaying

    Returns whether playback displays video.

    */
    inline bool isPlaying() const; //Returns the value of isPlaying

    /*
    Property itemCount

    Returns number of items in playlist. (deprecated)

    */
    inline int itemCount() const; //Returns the value of itemCount

    /*
    Property items

    Returns the playlist items collection object.

    */
    inline AXVLC::IVLCPlaylistItems* items() const; //Returns the value of items

    /*
    Method add

    Add a playlist item.

    */
    inline int add(const QString& uri);

    /*
    Method add

    Add a playlist item.

    */
    inline int add(const QString& uri, const QVariant& name);

    /*
    Method add

    Add a playlist item.

    */
    inline int add(const QString& uri, const QVariant& name, const QVariant& options);

    /*
    Method clear

    Remove all items from playlist. (deprecated)

    */
    inline void clear();

    /*
    Method next

    Advance to next item in playlist.

    */
    inline void next();

    /*
    Method play

    Play/Resume the playlist.

    */
    inline void play();

    /*
    Method playItem

    Play item in playlist.

    */
    inline void playItem(int itemId);

    /*
    Method prev

    Advance to previous item in playlist.

    */
    inline void prev();

    /*
    Method removeItem

    Remove item from playlist. (deprecated)

    */
    inline void removeItem(int item);

    /*
    Method stop

    Stop current clip.

    */
    inline void stop();

    /*
    Method togglePause

    Play/Pause current clip.

    */
    inline void togglePause();

// meta object functions
    static const QMetaObject staticMetaObject;
    virtual const QMetaObject *metaObject() const { return &staticMetaObject; }
    virtual void *qt_metacast(const char *);
};

class AXVLC_EXPORT IVLCPlaylistItems : public QAxObject
{
public:
    IVLCPlaylistItems(IDispatch *subobject = 0, QAxObject *parent = 0)
    : QAxObject((IUnknown*)subobject, parent)
    {
        internalRelease();
    }

    /*
    Property count

    Returns number of items in playlist.

    */
    inline int count() const; //Returns the value of count

    /*
    Method clear

    Remove all items from playlist.

    */
    inline void clear();

    /*
    Method remove

    remove item from playlist.

    */
    inline void remove(int itemId);

// meta object functions
    static const QMetaObject staticMetaObject;
    virtual const QMetaObject *metaObject() const { return &staticMetaObject; }
    virtual void *qt_metacast(const char *);
};

class AXVLC_EXPORT IVLCVideo : public QAxObject
{
public:
    IVLCVideo(IDispatch *subobject = 0, QAxObject *parent = 0)
    : QAxObject((IUnknown*)subobject, parent)
    {
        internalRelease();
    }

    /*
    Property aspectRatio

    Returns video aspect ratio.

    */
    inline QString aspectRatio() const; //Returns the value of aspectRatio
    inline void setAspectRatio(const QString& value); //Sets the value of the aspectRatio property

    /*
    Property crop

    Returns crop filter geometry.

    */
    inline QString crop() const; //Returns the value of crop
    inline void setCrop(const QString& value); //Sets the value of the crop property

    /*
    Property fullscreen

    Returns/sets the fullscreen state.

    */
    inline bool fullscreen() const; //Returns the value of fullscreen
    inline void setFullscreen(bool value); //Sets the value of the fullscreen property

    /*
    Property height

    Returns video original height.

    */
    inline int height() const; //Returns the value of height

    /*
    Property subtitle

    Returns video subtitle used.

    */
    inline int subtitle() const; //Returns the value of subtitle
    inline void setSubtitle(int value); //Sets the value of the subtitle property

    /*
    Property teletext

    Returns teletext page used.

    */
    inline int teletext() const; //Returns the value of teletext
    inline void setTeletext(int value); //Sets the value of the teletext property

    /*
    Property width

    Returns video original width.

    */
    inline int width() const; //Returns the value of width

    /*
    Method takeSnapshot

    take video snapshot and save it into picture object.

    */
    inline QPixmap takeSnapshot();

    /*
    Method toggleFullscreen

    toggle fullscreen/windowed state.

    */
    inline void toggleFullscreen();

    /*
    Method toggleTeletext

    toggle teletext transparent state.

    */
    inline void toggleTeletext();

// meta object functions
    static const QMetaObject staticMetaObject;
    virtual const QMetaObject *metaObject() const { return &staticMetaObject; }
    virtual void *qt_metacast(const char *);
};

class AXVLC_EXPORT IVLCControl2 : public QAxObject
{
public:
    IVLCControl2(IDispatch *subobject = 0, QAxObject *parent = 0)
    : QAxObject((IUnknown*)subobject, parent)
    {
        internalRelease();
    }

    /*
    Property AutoLoop

    Returns/sets a value that determines whether the playlist is looped

    */
    inline bool AutoLoop() const; //Returns the value of AutoLoop
    inline void SetAutoLoop(bool value); //Sets the value of the AutoLoop property

    /*
    Property AutoPlay

    Returns/sets a value that determines whether the playlist is played on startup

    */
    inline bool AutoPlay() const; //Returns the value of AutoPlay
    inline void SetAutoPlay(bool value); //Sets the value of the AutoPlay property

    /*
    Property BackColor

    Returns/sets background color.

    */
    inline QColor BackColor() const; //Returns the value of BackColor
    inline void SetBackColor(const QColor& value); //Sets the value of the BackColor property

    /*
    Property BaseURL

    Returns/sets the base URL for relative paths

    */
    inline QString BaseURL() const; //Returns the value of BaseURL
    inline void SetBaseURL(const QString& value); //Sets the value of the BaseURL property

    /*
    Property MRL

    Returns/sets the default MRL in playlist

    */
    inline QString MRL() const; //Returns the value of MRL
    inline void SetMRL(const QString& value); //Sets the value of the MRL property

    /*
    Property StartTime

    Returns/sets playback start time of URL.

    */
    inline int StartTime() const; //Returns the value of StartTime
    inline void SetStartTime(int value); //Sets the value of the StartTime property

    /*
    Property Toolbar

    Returns/sets visibility of the toolbar

    */
    inline bool Toolbar() const; //Returns the value of Toolbar
    inline void SetToolbar(bool value); //Sets the value of the Toolbar property

    /*
    Property VersionInfo

    Returns VLC Version.

    */
    inline QString VersionInfo() const; //Returns the value of VersionInfo

    /*
    Property Visible

    Returns/sets a value that determines whether viewing area is visible or hidden.

    */
    inline bool Visible() const; //Returns the value of Visible
    inline void SetVisible(bool value); //Sets the value of the Visible property

    /*
    Property Volume

    Returns/sets default audio volume.

    */
    inline int Volume() const; //Returns the value of Volume
    inline void SetVolume(int value); //Sets the value of the Volume property

    /*
    Property audio

    Returns the audio object.

    */
    inline AXVLC::IVLCAudio* audio() const; //Returns the value of audio

    /*
    Property input

    Returns the audio object.

    */
    inline AXVLC::IVLCInput* input() const; //Returns the value of input

    /*
    Property log

    Returns the log object.

    */
    inline AXVLC::IVLCLog* log() const; //Returns the value of log

    /*
    Property playlist

    Returns the playlist object.

    */
    inline AXVLC::IVLCPlaylist* playlist() const; //Returns the value of playlist

    /*
    Property video

    Returns the audio object.

    */
    inline AXVLC::IVLCVideo* video() const; //Returns the value of video

// meta object functions
    static const QMetaObject staticMetaObject;
    virtual const QMetaObject *metaObject() const { return &staticMetaObject; }
    virtual void *qt_metacast(const char *);
};

// skipping event interface DVLCEvents

// Actual coclasses
class AXVLC_EXPORT VLCPlugin : public QAxWidget
{
public:
    VLCPlugin(QWidget *parent = 0, Qt::WindowFlags f = 0)
    : QAxWidget(parent, f)
    {
        setControl("{e23fe9c6-778e-49d4-b537-38fcde4887d8}");
    }

    VLCPlugin(IVLCControl *iface)
    : QAxWidget()
    {
        initializeFrom(iface);
        delete iface;
    }

    VLCPlugin(IVLCControl2 *iface)
    : QAxWidget()
    {
        initializeFrom(iface);
        delete iface;
    }

    /*
    Property AutoLoop

    Returns/sets a value that determines whether the playlist is looped

    */
    inline bool AutoLoop() const; //Returns the value of AutoLoop
    inline void SetAutoLoop(bool value); //Sets the value of the AutoLoop property

    /*
    Property AutoPlay

    Returns/sets a value that determines whether the playlist is played on startup

    */
    inline bool AutoPlay() const; //Returns the value of AutoPlay
    inline void SetAutoPlay(bool value); //Sets the value of the AutoPlay property

    /*
    Property BackColor
    */
    inline QColor BackColor() const; //Returns the value of BackColor
    inline void SetBackColor(const QColor& value); //Sets the value of the BackColor property

    /*
    Property BaseURL
    */
    inline QString BaseURL() const; //Returns the value of BaseURL
    inline void SetBaseURL(const QString& value); //Sets the value of the BaseURL property

    /*
    Property Length

    Returns the total length, in seconds, of the current item, may be unknown.

    */
    inline int Length() const; //Returns the value of Length

    /*
    Property MRL

    Returns/sets the first MRL in playlist, used for AutoPlay

    */
    inline QString MRL() const; //Returns the value of MRL
    inline void SetMRL(const QString& value); //Sets the value of the MRL property

    /*
    Property Playing

    Returns a value that determines whether VLC is currently playing.

    */
    inline bool Playing() const; //Returns the value of Playing

    /*
    Property PlaylistCount

    Returns number of items in playlist.

    */
    inline int PlaylistCount() const; //Returns the value of PlaylistCount

    /*
    Property PlaylistIndex

    Returns index of current item in playlist.

    */
    inline int PlaylistIndex() const; //Returns the value of PlaylistIndex

    /*
    Property Position

    Returns/sets playback position within the current item. Position is a relative value ranging from 0.0 to 1.0.

    */
    inline double Position() const; //Returns the value of Position
    inline void SetPosition(double value); //Sets the value of the Position property

    /*
    Property StartTime
    */
    inline int StartTime() const; //Returns the value of StartTime
    inline void SetStartTime(int value); //Sets the value of the StartTime property

    /*
    Property Time

    Returns/sets playback time relative to the start of the current item.

    */
    inline int Time() const; //Returns the value of Time
    inline void SetTime(int value); //Sets the value of the Time property

    /*
    Property Toolbar
    */
    inline bool Toolbar() const; //Returns the value of Toolbar
    inline void SetToolbar(bool value); //Sets the value of the Toolbar property

    /*
    Property VersionInfo

    Returns VLC Version.

    */
    inline QString VersionInfo() const; //Returns the value of VersionInfo

    /*
    Property Visible

    Returns/sets a value that determines whether viewing area is visible or hidden.

    */
    inline bool Visible() const; //Returns the value of Visible
    inline void SetVisible(bool value); //Sets the value of the Visible property

    /*
    Property Volume

    Returns/sets playback volume, ranges from 0 to 200%.

    */
    inline int Volume() const; //Returns the value of Volume
    inline void SetVolume(int value); //Sets the value of the Volume property

    /*
    Property audio
    */
    inline AXVLC::IVLCAudio* audio() const; //Returns the value of audio

    /*
    Property input
    */
    inline AXVLC::IVLCInput* input() const; //Returns the value of input

    /*
    Property log
    */
    inline AXVLC::IVLCLog* log() const; //Returns the value of log

    /*
    Property playlist
    */
    inline AXVLC::IVLCPlaylist* playlist() const; //Returns the value of playlist

    /*
    Property video
    */
    inline AXVLC::IVLCVideo* video() const; //Returns the value of video

    /*
    Method addTarget

    Add an item to the playlist.

    */
    inline void addTarget(const QString& uri, const QVariant& options, AXVLC::VLCPlaylistMode mode, int Position);

    /*
    Method fullscreen

    Switch video between normal and fullscreen view modes.

    */
    inline void fullscreen();

    /*
    Method getVariable

    Returns the value of a VLC variable.

    */
    inline QVariant getVariable(const QString& name);

    /*
    Method pause

    Pause playback.

    */
    inline void pause();

    /*
    Method play

    Play current target in playlist.

    */
    inline void play();

    /*
    Method playFaster

    Increases playback speed. Possible speeds are: 1x, 2x, 4x, 8x.

    */
    inline void playFaster();

    /*
    Method playSlower

    Decreases playback speed. Possible speeds are: 1x, 2x, 4x, 8x.

    */
    inline void playSlower();

    /*
    Method playlistClear

    Remove all items from playlist.

    */
    inline void playlistClear();

    /*
    Method playlistNext

    Advance to next item in playlist.

    */
    inline void playlistNext();

    /*
    Method playlistPrev

    Advance to previous item in playlist.

    */
    inline void playlistPrev();

    /*
    Method setVariable

    Sets the value of a VLC variable.

    */
    inline void setVariable(const QString& name, const QVariant& value);

    /*
    Method shuttle

    Advance or backtrack playback time, relative to current time.

    */
    inline void shuttle(int seconds);

    /*
    Method stop

    Stop playback.

    */
    inline void stop();

    /*
    Method toggleMute

    Mute/unmute playback audio.

    */
    inline void toggleMute();

// meta object functions
    static const QMetaObject staticMetaObject;
    virtual const QMetaObject *metaObject() const { return &staticMetaObject; }
    virtual void *qt_metacast(const char *);
};

class AXVLC_EXPORT VLCPlugin2 : public QAxWidget
{
public:
    VLCPlugin2(QWidget *parent = 0, Qt::WindowFlags f = 0)
    : QAxWidget(parent, f)
    {
        setControl("{9be31822-fdad-461b-ad51-be1d1c159921}");
    }

    VLCPlugin2(IVLCControl2 *iface)
    : QAxWidget()
    {
        initializeFrom(iface);
        delete iface;
    }

    VLCPlugin2(IVLCControl *iface)
    : QAxWidget()
    {
        initializeFrom(iface);
        delete iface;
    }

    /*
    Property AutoLoop

    Returns/sets a value that determines whether the playlist is looped

    */
    inline bool AutoLoop() const; //Returns the value of AutoLoop
    inline void SetAutoLoop(bool value); //Sets the value of the AutoLoop property

    /*
    Property AutoPlay

    Returns/sets a value that determines whether the playlist is played on startup

    */
    inline bool AutoPlay() const; //Returns the value of AutoPlay
    inline void SetAutoPlay(bool value); //Sets the value of the AutoPlay property

    /*
    Property BackColor

    Returns/sets background color.

    */
    inline QColor BackColor() const; //Returns the value of BackColor
    inline void SetBackColor(const QColor& value); //Sets the value of the BackColor property

    /*
    Property BaseURL

    Returns/sets the base URL for relative paths

    */
    inline QString BaseURL() const; //Returns the value of BaseURL
    inline void SetBaseURL(const QString& value); //Sets the value of the BaseURL property

    /*
    Property Length
    */
    inline int Length() const; //Returns the value of Length

    /*
    Property MRL

    Returns/sets the default MRL in playlist

    */
    inline QString MRL() const; //Returns the value of MRL
    inline void SetMRL(const QString& value); //Sets the value of the MRL property

    /*
    Property Playing
    */
    inline bool Playing() const; //Returns the value of Playing

    /*
    Property PlaylistCount
    */
    inline int PlaylistCount() const; //Returns the value of PlaylistCount

    /*
    Property PlaylistIndex
    */
    inline int PlaylistIndex() const; //Returns the value of PlaylistIndex

    /*
    Property Position
    */
    inline double Position() const; //Returns the value of Position
    inline void SetPosition(double value); //Sets the value of the Position property

    /*
    Property StartTime

    Returns/sets playback start time of URL.

    */
    inline int StartTime() const; //Returns the value of StartTime
    inline void SetStartTime(int value); //Sets the value of the StartTime property

    /*
    Property Time
    */
    inline int Time() const; //Returns the value of Time
    inline void SetTime(int value); //Sets the value of the Time property

    /*
    Property Toolbar

    Returns/sets visibility of the toolbar

    */
    inline bool Toolbar() const; //Returns the value of Toolbar
    inline void SetToolbar(bool value); //Sets the value of the Toolbar property

    /*
    Property VersionInfo

    Returns VLC Version.

    */
    inline QString VersionInfo() const; //Returns the value of VersionInfo

    /*
    Property Visible

    Returns/sets a value that determines whether viewing area is visible or hidden.

    */
    inline bool Visible() const; //Returns the value of Visible
    inline void SetVisible(bool value); //Sets the value of the Visible property

    /*
    Property Volume

    Returns/sets default audio volume.

    */
    inline int Volume() const; //Returns the value of Volume
    inline void SetVolume(int value); //Sets the value of the Volume property

    /*
    Property audio

    Returns the audio object.

    */
    inline AXVLC::IVLCAudio* audio() const; //Returns the value of audio

    /*
    Property input

    Returns the audio object.

    */
    inline AXVLC::IVLCInput* input() const; //Returns the value of input

    /*
    Property log

    Returns the log object.

    */
    inline AXVLC::IVLCLog* log() const; //Returns the value of log

    /*
    Property playlist

    Returns the playlist object.

    */
    inline AXVLC::IVLCPlaylist* playlist() const; //Returns the value of playlist

    /*
    Property video

    Returns the audio object.

    */
    inline AXVLC::IVLCVideo* video() const; //Returns the value of video

    /*
    Method addTarget
    */
    inline void addTarget(const QString& uri, const QVariant& options, AXVLC::VLCPlaylistMode mode, int Position);

    /*
    Method fullscreen
    */
    inline void fullscreen();

    /*
    Method getVariable
    */
    inline QVariant getVariable(const QString& name);

    /*
    Method pause
    */
    inline void pause();

    /*
    Method play
    */
    inline void play();

    /*
    Method playFaster
    */
    inline void playFaster();

    /*
    Method playSlower
    */
    inline void playSlower();

    /*
    Method playlistClear
    */
    inline void playlistClear();

    /*
    Method playlistNext
    */
    inline void playlistNext();

    /*
    Method playlistPrev
    */
    inline void playlistPrev();

    /*
    Method setVariable
    */
    inline void setVariable(const QString& name, const QVariant& value);

    /*
    Method shuttle
    */
    inline void shuttle(int seconds);

    /*
    Method stop
    */
    inline void stop();

    /*
    Method toggleMute
    */
    inline void toggleMute();

// meta object functions
    static const QMetaObject staticMetaObject;
    virtual const QMetaObject *metaObject() const { return &staticMetaObject; }
    virtual void *qt_metacast(const char *);
};

// member function implementation
#ifndef QAX_DUMPCPP_AXVLC_NOINLINES
inline bool IVLCControl::AutoLoop() const
{
    QVariant qax_result = property("AutoLoop");
    Q_ASSERT(qax_result.isValid());
    return *(bool*)qax_result.constData();
}
inline void IVLCControl::SetAutoLoop(bool value){ setProperty("AutoLoop", QVariant(value)); }

inline bool IVLCControl::AutoPlay() const
{
    QVariant qax_result = property("AutoPlay");
    Q_ASSERT(qax_result.isValid());
    return *(bool*)qax_result.constData();
}
inline void IVLCControl::SetAutoPlay(bool value){ setProperty("AutoPlay", QVariant(value)); }

inline int IVLCControl::Length() const
{
    QVariant qax_result = property("Length");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}

inline QString IVLCControl::MRL() const
{
    QVariant qax_result = property("MRL");
    Q_ASSERT(qax_result.isValid());
    return *(QString*)qax_result.constData();
}
inline void IVLCControl::SetMRL(const QString& value){ setProperty("MRL", QVariant(value)); }

inline bool IVLCControl::Playing() const
{
    QVariant qax_result = property("Playing");
    Q_ASSERT(qax_result.isValid());
    return *(bool*)qax_result.constData();
}

inline int IVLCControl::PlaylistCount() const
{
    QVariant qax_result = property("PlaylistCount");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}

inline int IVLCControl::PlaylistIndex() const
{
    QVariant qax_result = property("PlaylistIndex");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}

inline double IVLCControl::Position() const
{
    QVariant qax_result = property("Position");
    Q_ASSERT(qax_result.isValid());
    return *(double*)qax_result.constData();
}
inline void IVLCControl::SetPosition(double value){ setProperty("Position", QVariant(value)); }

inline int IVLCControl::Time() const
{
    QVariant qax_result = property("Time");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}
inline void IVLCControl::SetTime(int value){ setProperty("Time", QVariant(value)); }

inline QString IVLCControl::VersionInfo() const
{
    QVariant qax_result = property("VersionInfo");
    Q_ASSERT(qax_result.isValid());
    return *(QString*)qax_result.constData();
}

inline bool IVLCControl::Visible() const
{
    QVariant qax_result = property("Visible");
    Q_ASSERT(qax_result.isValid());
    return *(bool*)qax_result.constData();
}
inline void IVLCControl::SetVisible(bool value){ setProperty("Visible", QVariant(value)); }

inline int IVLCControl::Volume() const
{
    QVariant qax_result = property("Volume");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}
inline void IVLCControl::SetVolume(int value){ setProperty("Volume", QVariant(value)); }

inline void IVLCControl::addTarget(const QString& uri, const QVariant& options, AXVLC::VLCPlaylistMode mode, int Position)
{
    void *_a[] = {0, (void*)&uri, (void*)&options, (void*)&mode, (void*)&Position};
    qt_metacall(QMetaObject::InvokeMetaMethod, 15, _a);
}

inline void IVLCControl::fullscreen()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 16, _a);
}

inline QVariant IVLCControl::getVariable(const QString& name)
{
    QVariant qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&name};
    qt_metacall(QMetaObject::InvokeMetaMethod, 17, _a);
    return qax_result;
}

inline void IVLCControl::pause()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 18, _a);
}

inline void IVLCControl::play()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 19, _a);
}

inline void IVLCControl::playFaster()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 20, _a);
}

inline void IVLCControl::playSlower()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 21, _a);
}

inline void IVLCControl::playlistClear()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 22, _a);
}

inline void IVLCControl::playlistNext()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 23, _a);
}

inline void IVLCControl::playlistPrev()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 24, _a);
}

inline void IVLCControl::setVariable(const QString& name, const QVariant& value)
{
    void *_a[] = {0, (void*)&name, (void*)&value};
    qt_metacall(QMetaObject::InvokeMetaMethod, 25, _a);
}

inline void IVLCControl::shuttle(int seconds)
{
    void *_a[] = {0, (void*)&seconds};
    qt_metacall(QMetaObject::InvokeMetaMethod, 26, _a);
}

inline void IVLCControl::stop()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 27, _a);
}

inline void IVLCControl::toggleMute()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 28, _a);
}


inline int IVLCAudio::Volume() const
{
    QVariant qax_result = property("Volume");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}
inline void IVLCAudio::SetVolume(int value){ setProperty("Volume", QVariant(value)); }

inline int IVLCAudio::channel() const
{
    QVariant qax_result = property("channel");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}
inline void IVLCAudio::setChannel(int value){ setProperty("channel", QVariant(value)); }

inline bool IVLCAudio::mute() const
{
    QVariant qax_result = property("mute");
    Q_ASSERT(qax_result.isValid());
    return *(bool*)qax_result.constData();
}
inline void IVLCAudio::setMute(bool value){ setProperty("mute", QVariant(value)); }

inline int IVLCAudio::track() const
{
    QVariant qax_result = property("track");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}
inline void IVLCAudio::setTrack(int value){ setProperty("track", QVariant(value)); }

inline void IVLCAudio::toggleMute()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 11, _a);
}


inline double IVLCInput::Length() const
{
    QVariant qax_result = property("Length");
    Q_ASSERT(qax_result.isValid());
    return *(double*)qax_result.constData();
}

inline double IVLCInput::Position() const
{
    QVariant qax_result = property("Position");
    Q_ASSERT(qax_result.isValid());
    return *(double*)qax_result.constData();
}
inline void IVLCInput::SetPosition(double value){ setProperty("Position", QVariant(value)); }

inline double IVLCInput::Time() const
{
    QVariant qax_result = property("Time");
    Q_ASSERT(qax_result.isValid());
    return *(double*)qax_result.constData();
}
inline void IVLCInput::SetTime(double value){ setProperty("Time", QVariant(value)); }

inline double IVLCInput::fps() const
{
    QVariant qax_result = property("fps");
    Q_ASSERT(qax_result.isValid());
    return *(double*)qax_result.constData();
}

inline bool IVLCInput::hasVout() const
{
    QVariant qax_result = property("hasVout");
    Q_ASSERT(qax_result.isValid());
    return *(bool*)qax_result.constData();
}

inline double IVLCInput::rate() const
{
    QVariant qax_result = property("rate");
    Q_ASSERT(qax_result.isValid());
    return *(double*)qax_result.constData();
}
inline void IVLCInput::setRate(double value){ setProperty("rate", QVariant(value)); }

inline int IVLCInput::state() const
{
    QVariant qax_result = property("state");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}


inline AXVLC::IVLCMessages* IVLCLog::messages() const
{
    AXVLC::IVLCMessages* qax_pointer = 0;
    qRegisterMetaType("IVLCMessages*", &qax_pointer);
    qRegisterMetaType("IVLCMessages", qax_pointer);
    QVariant qax_result = property("messages");
    if (!qax_result.constData()) return 0;
    Q_ASSERT(qax_result.isValid());
    return *(AXVLC::IVLCMessages**)qax_result.constData();
}

inline int IVLCLog::verbosity() const
{
    QVariant qax_result = property("verbosity");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}
inline void IVLCLog::setVerbosity(int value){ setProperty("verbosity", QVariant(value)); }


inline IUnknown* IVLCMessages::_NewEnum() const
{
    QVariant qax_result = property("_NewEnum");
    if (!qax_result.constData()) return 0;
    Q_ASSERT(qax_result.isValid());
    return *(IUnknown**)qax_result.constData();
}

inline int IVLCMessages::count() const
{
    QVariant qax_result = property("count");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}

inline void IVLCMessages::clear()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 7, _a);
}

inline AXVLC::IVLCMessageIterator* IVLCMessages::iterator()
{
    AXVLC::IVLCMessageIterator* qax_result = 0;
    qRegisterMetaType("IVLCMessageIterator*", &qax_result);
    qRegisterMetaType("IVLCMessageIterator", qax_result);
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 8, _a);
    return qax_result;
}


inline bool IVLCMessageIterator::hasNext() const
{
    QVariant qax_result = property("hasNext");
    Q_ASSERT(qax_result.isValid());
    return *(bool*)qax_result.constData();
}

inline AXVLC::IVLCMessage* IVLCMessageIterator::next()
{
    AXVLC::IVLCMessage* qax_result = 0;
    qRegisterMetaType("IVLCMessage*", &qax_result);
    qRegisterMetaType("IVLCMessage", qax_result);
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 7, _a);
    return qax_result;
}


inline QVariant IVLCMessage::_Value() const
{
    QVariant qax_result = property("_Value");
    Q_ASSERT(qax_result.isValid());
    return *(QVariant*)qax_result.constData();
}

inline QString IVLCMessage::header() const
{
    QVariant qax_result = property("header");
    Q_ASSERT(qax_result.isValid());
    return *(QString*)qax_result.constData();
}

inline QString IVLCMessage::message() const
{
    QVariant qax_result = property("message");
    Q_ASSERT(qax_result.isValid());
    return *(QString*)qax_result.constData();
}

inline QString IVLCMessage::name() const
{
    QVariant qax_result = property("name");
    Q_ASSERT(qax_result.isValid());
    return *(QString*)qax_result.constData();
}

inline int IVLCMessage::severity() const
{
    QVariant qax_result = property("severity");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}

inline QString IVLCMessage::type() const
{
    QVariant qax_result = property("type");
    Q_ASSERT(qax_result.isValid());
    return *(QString*)qax_result.constData();
}


inline bool IVLCPlaylist::isPlaying() const
{
    QVariant qax_result = property("isPlaying");
    Q_ASSERT(qax_result.isValid());
    return *(bool*)qax_result.constData();
}

inline int IVLCPlaylist::itemCount() const
{
    QVariant qax_result = property("itemCount");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}

inline AXVLC::IVLCPlaylistItems* IVLCPlaylist::items() const
{
    AXVLC::IVLCPlaylistItems* qax_pointer = 0;
    qRegisterMetaType("IVLCPlaylistItems*", &qax_pointer);
    qRegisterMetaType("IVLCPlaylistItems", qax_pointer);
    QVariant qax_result = property("items");
    if (!qax_result.constData()) return 0;
    Q_ASSERT(qax_result.isValid());
    return *(AXVLC::IVLCPlaylistItems**)qax_result.constData();
}

inline int IVLCPlaylist::add(const QString& uri)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&uri};
    qt_metacall(QMetaObject::InvokeMetaMethod, 7, _a);
    return qax_result;
}

inline int IVLCPlaylist::add(const QString& uri, const QVariant& name)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&uri, (void*)&name};
    qt_metacall(QMetaObject::InvokeMetaMethod, 8, _a);
    return qax_result;
}

inline int IVLCPlaylist::add(const QString& uri, const QVariant& name, const QVariant& options)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&uri, (void*)&name, (void*)&options};
    qt_metacall(QMetaObject::InvokeMetaMethod, 9, _a);
    return qax_result;
}

inline void IVLCPlaylist::clear()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 10, _a);
}

inline void IVLCPlaylist::next()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 11, _a);
}

inline void IVLCPlaylist::play()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 12, _a);
}

inline void IVLCPlaylist::playItem(int itemId)
{
    void *_a[] = {0, (void*)&itemId};
    qt_metacall(QMetaObject::InvokeMetaMethod, 13, _a);
}

inline void IVLCPlaylist::prev()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 14, _a);
}

inline void IVLCPlaylist::removeItem(int item)
{
    void *_a[] = {0, (void*)&item};
    qt_metacall(QMetaObject::InvokeMetaMethod, 15, _a);
}

inline void IVLCPlaylist::stop()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 16, _a);
}

inline void IVLCPlaylist::togglePause()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 17, _a);
}


inline int IVLCPlaylistItems::count() const
{
    QVariant qax_result = property("count");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}

inline void IVLCPlaylistItems::clear()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 7, _a);
}

inline void IVLCPlaylistItems::remove(int itemId)
{
    void *_a[] = {0, (void*)&itemId};
    qt_metacall(QMetaObject::InvokeMetaMethod, 8, _a);
}


inline QString IVLCVideo::aspectRatio() const
{
    QVariant qax_result = property("aspectRatio");
    Q_ASSERT(qax_result.isValid());
    return *(QString*)qax_result.constData();
}
inline void IVLCVideo::setAspectRatio(const QString& value){ setProperty("aspectRatio", QVariant(value)); }

inline QString IVLCVideo::crop() const
{
    QVariant qax_result = property("crop");
    Q_ASSERT(qax_result.isValid());
    return *(QString*)qax_result.constData();
}
inline void IVLCVideo::setCrop(const QString& value){ setProperty("crop", QVariant(value)); }

inline bool IVLCVideo::fullscreen() const
{
    QVariant qax_result = property("fullscreen");
    Q_ASSERT(qax_result.isValid());
    return *(bool*)qax_result.constData();
}
inline void IVLCVideo::setFullscreen(bool value){ setProperty("fullscreen", QVariant(value)); }

inline int IVLCVideo::height() const
{
    QVariant qax_result = property("height");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}

inline int IVLCVideo::subtitle() const
{
    QVariant qax_result = property("subtitle");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}
inline void IVLCVideo::setSubtitle(int value){ setProperty("subtitle", QVariant(value)); }

inline int IVLCVideo::teletext() const
{
    QVariant qax_result = property("teletext");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}
inline void IVLCVideo::setTeletext(int value){ setProperty("teletext", QVariant(value)); }

inline int IVLCVideo::width() const
{
    QVariant qax_result = property("width");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}

inline QPixmap IVLCVideo::takeSnapshot()
{
    QPixmap qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 12, _a);
    return qax_result;
}

inline void IVLCVideo::toggleFullscreen()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 13, _a);
}

inline void IVLCVideo::toggleTeletext()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 14, _a);
}


inline bool IVLCControl2::AutoLoop() const
{
    QVariant qax_result = property("AutoLoop");
    Q_ASSERT(qax_result.isValid());
    return *(bool*)qax_result.constData();
}
inline void IVLCControl2::SetAutoLoop(bool value){ setProperty("AutoLoop", QVariant(value)); }

inline bool IVLCControl2::AutoPlay() const
{
    QVariant qax_result = property("AutoPlay");
    Q_ASSERT(qax_result.isValid());
    return *(bool*)qax_result.constData();
}
inline void IVLCControl2::SetAutoPlay(bool value){ setProperty("AutoPlay", QVariant(value)); }

inline QColor IVLCControl2::BackColor() const
{
    QVariant qax_result = property("BackColor");
    Q_ASSERT(qax_result.isValid());
    return *(QColor*)qax_result.constData();
}
inline void IVLCControl2::SetBackColor(const QColor& value){ setProperty("BackColor", QVariant(value)); }

inline QString IVLCControl2::BaseURL() const
{
    QVariant qax_result = property("BaseURL");
    Q_ASSERT(qax_result.isValid());
    return *(QString*)qax_result.constData();
}
inline void IVLCControl2::SetBaseURL(const QString& value){ setProperty("BaseURL", QVariant(value)); }

inline QString IVLCControl2::MRL() const
{
    QVariant qax_result = property("MRL");
    Q_ASSERT(qax_result.isValid());
    return *(QString*)qax_result.constData();
}
inline void IVLCControl2::SetMRL(const QString& value){ setProperty("MRL", QVariant(value)); }

inline int IVLCControl2::StartTime() const
{
    QVariant qax_result = property("StartTime");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}
inline void IVLCControl2::SetStartTime(int value){ setProperty("StartTime", QVariant(value)); }

inline bool IVLCControl2::Toolbar() const
{
    QVariant qax_result = property("Toolbar");
    Q_ASSERT(qax_result.isValid());
    return *(bool*)qax_result.constData();
}
inline void IVLCControl2::SetToolbar(bool value){ setProperty("Toolbar", QVariant(value)); }

inline QString IVLCControl2::VersionInfo() const
{
    QVariant qax_result = property("VersionInfo");
    Q_ASSERT(qax_result.isValid());
    return *(QString*)qax_result.constData();
}

inline bool IVLCControl2::Visible() const
{
    QVariant qax_result = property("Visible");
    Q_ASSERT(qax_result.isValid());
    return *(bool*)qax_result.constData();
}
inline void IVLCControl2::SetVisible(bool value){ setProperty("Visible", QVariant(value)); }

inline int IVLCControl2::Volume() const
{
    QVariant qax_result = property("Volume");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}
inline void IVLCControl2::SetVolume(int value){ setProperty("Volume", QVariant(value)); }

inline AXVLC::IVLCAudio* IVLCControl2::audio() const
{
    AXVLC::IVLCAudio* qax_pointer = 0;
    qRegisterMetaType("IVLCAudio*", &qax_pointer);
    qRegisterMetaType("IVLCAudio", qax_pointer);
    QVariant qax_result = property("audio");
    if (!qax_result.constData()) return 0;
    Q_ASSERT(qax_result.isValid());
    return *(AXVLC::IVLCAudio**)qax_result.constData();
}

inline AXVLC::IVLCInput* IVLCControl2::input() const
{
    AXVLC::IVLCInput* qax_pointer = 0;
    qRegisterMetaType("IVLCInput*", &qax_pointer);
    qRegisterMetaType("IVLCInput", qax_pointer);
    QVariant qax_result = property("input");
    if (!qax_result.constData()) return 0;
    Q_ASSERT(qax_result.isValid());
    return *(AXVLC::IVLCInput**)qax_result.constData();
}

inline AXVLC::IVLCLog* IVLCControl2::log() const
{
    AXVLC::IVLCLog* qax_pointer = 0;
    qRegisterMetaType("IVLCLog*", &qax_pointer);
    qRegisterMetaType("IVLCLog", qax_pointer);
    QVariant qax_result = property("log");
    if (!qax_result.constData()) return 0;
    Q_ASSERT(qax_result.isValid());
    return *(AXVLC::IVLCLog**)qax_result.constData();
}

inline AXVLC::IVLCPlaylist* IVLCControl2::playlist() const
{
    AXVLC::IVLCPlaylist* qax_pointer = 0;
    qRegisterMetaType("IVLCPlaylist*", &qax_pointer);
    qRegisterMetaType("IVLCPlaylist", qax_pointer);
    QVariant qax_result = property("playlist");
    if (!qax_result.constData()) return 0;
    Q_ASSERT(qax_result.isValid());
    return *(AXVLC::IVLCPlaylist**)qax_result.constData();
}

inline AXVLC::IVLCVideo* IVLCControl2::video() const
{
    AXVLC::IVLCVideo* qax_pointer = 0;
    qRegisterMetaType("IVLCVideo*", &qax_pointer);
    qRegisterMetaType("IVLCVideo", qax_pointer);
    QVariant qax_result = property("video");
    if (!qax_result.constData()) return 0;
    Q_ASSERT(qax_result.isValid());
    return *(AXVLC::IVLCVideo**)qax_result.constData();
}


inline bool VLCPlugin::AutoLoop() const
{
    QVariant qax_result = property("AutoLoop");
    Q_ASSERT(qax_result.isValid());
    return *(bool*)qax_result.constData();
}
inline void VLCPlugin::SetAutoLoop(bool value){ setProperty("AutoLoop", QVariant(value)); }

inline bool VLCPlugin::AutoPlay() const
{
    QVariant qax_result = property("AutoPlay");
    Q_ASSERT(qax_result.isValid());
    return *(bool*)qax_result.constData();
}
inline void VLCPlugin::SetAutoPlay(bool value){ setProperty("AutoPlay", QVariant(value)); }

inline QColor VLCPlugin::BackColor() const
{
    QVariant qax_result = property("BackColor");
    Q_ASSERT(qax_result.isValid());
    return *(QColor*)qax_result.constData();
}
inline void VLCPlugin::SetBackColor(const QColor& value){ setProperty("BackColor", QVariant(value)); }

inline QString VLCPlugin::BaseURL() const
{
    QVariant qax_result = property("BaseURL");
    Q_ASSERT(qax_result.isValid());
    return *(QString*)qax_result.constData();
}
inline void VLCPlugin::SetBaseURL(const QString& value){ setProperty("BaseURL", QVariant(value)); }

inline int VLCPlugin::Length() const
{
    QVariant qax_result = property("Length");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}

inline QString VLCPlugin::MRL() const
{
    QVariant qax_result = property("MRL");
    Q_ASSERT(qax_result.isValid());
    return *(QString*)qax_result.constData();
}
inline void VLCPlugin::SetMRL(const QString& value){ setProperty("MRL", QVariant(value)); }

inline bool VLCPlugin::Playing() const
{
    QVariant qax_result = property("Playing");
    Q_ASSERT(qax_result.isValid());
    return *(bool*)qax_result.constData();
}

inline int VLCPlugin::PlaylistCount() const
{
    QVariant qax_result = property("PlaylistCount");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}

inline int VLCPlugin::PlaylistIndex() const
{
    QVariant qax_result = property("PlaylistIndex");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}

inline double VLCPlugin::Position() const
{
    QVariant qax_result = property("Position");
    Q_ASSERT(qax_result.isValid());
    return *(double*)qax_result.constData();
}
inline void VLCPlugin::SetPosition(double value){ setProperty("Position", QVariant(value)); }

inline int VLCPlugin::StartTime() const
{
    QVariant qax_result = property("StartTime");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}
inline void VLCPlugin::SetStartTime(int value){ setProperty("StartTime", QVariant(value)); }

inline int VLCPlugin::Time() const
{
    QVariant qax_result = property("Time");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}
inline void VLCPlugin::SetTime(int value){ setProperty("Time", QVariant(value)); }

inline bool VLCPlugin::Toolbar() const
{
    QVariant qax_result = property("Toolbar");
    Q_ASSERT(qax_result.isValid());
    return *(bool*)qax_result.constData();
}
inline void VLCPlugin::SetToolbar(bool value){ setProperty("Toolbar", QVariant(value)); }

inline QString VLCPlugin::VersionInfo() const
{
    QVariant qax_result = property("VersionInfo");
    Q_ASSERT(qax_result.isValid());
    return *(QString*)qax_result.constData();
}

inline bool VLCPlugin::Visible() const
{
    QVariant qax_result = property("Visible");
    Q_ASSERT(qax_result.isValid());
    return *(bool*)qax_result.constData();
}
inline void VLCPlugin::SetVisible(bool value){ setProperty("Visible", QVariant(value)); }

inline int VLCPlugin::Volume() const
{
    QVariant qax_result = property("Volume");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}
inline void VLCPlugin::SetVolume(int value){ setProperty("Volume", QVariant(value)); }

inline AXVLC::IVLCAudio* VLCPlugin::audio() const
{
    AXVLC::IVLCAudio* qax_pointer = 0;
    qRegisterMetaType("IVLCAudio*", &qax_pointer);
    qRegisterMetaType("IVLCAudio", qax_pointer);
    QVariant qax_result = property("audio");
    if (!qax_result.constData()) return 0;
    Q_ASSERT(qax_result.isValid());
    return *(AXVLC::IVLCAudio**)qax_result.constData();
}

inline AXVLC::IVLCInput* VLCPlugin::input() const
{
    AXVLC::IVLCInput* qax_pointer = 0;
    qRegisterMetaType("IVLCInput*", &qax_pointer);
    qRegisterMetaType("IVLCInput", qax_pointer);
    QVariant qax_result = property("input");
    if (!qax_result.constData()) return 0;
    Q_ASSERT(qax_result.isValid());
    return *(AXVLC::IVLCInput**)qax_result.constData();
}

inline AXVLC::IVLCLog* VLCPlugin::log() const
{
    AXVLC::IVLCLog* qax_pointer = 0;
    qRegisterMetaType("IVLCLog*", &qax_pointer);
    qRegisterMetaType("IVLCLog", qax_pointer);
    QVariant qax_result = property("log");
    if (!qax_result.constData()) return 0;
    Q_ASSERT(qax_result.isValid());
    return *(AXVLC::IVLCLog**)qax_result.constData();
}

inline AXVLC::IVLCPlaylist* VLCPlugin::playlist() const
{
    AXVLC::IVLCPlaylist* qax_pointer = 0;
    qRegisterMetaType("IVLCPlaylist*", &qax_pointer);
    qRegisterMetaType("IVLCPlaylist", qax_pointer);
    QVariant qax_result = property("playlist");
    if (!qax_result.constData()) return 0;
    Q_ASSERT(qax_result.isValid());
    return *(AXVLC::IVLCPlaylist**)qax_result.constData();
}

inline AXVLC::IVLCVideo* VLCPlugin::video() const
{
    AXVLC::IVLCVideo* qax_pointer = 0;
    qRegisterMetaType("IVLCVideo*", &qax_pointer);
    qRegisterMetaType("IVLCVideo", qax_pointer);
    QVariant qax_result = property("video");
    if (!qax_result.constData()) return 0;
    Q_ASSERT(qax_result.isValid());
    return *(AXVLC::IVLCVideo**)qax_result.constData();
}

inline void VLCPlugin::addTarget(const QString& uri, const QVariant& options, AXVLC::VLCPlaylistMode mode, int Position)
{
    void *_a[] = {0, (void*)&uri, (void*)&options, (void*)&mode, (void*)&Position};
    qt_metacall(QMetaObject::InvokeMetaMethod, 44, _a);
}

inline void VLCPlugin::fullscreen()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 45, _a);
}

inline QVariant VLCPlugin::getVariable(const QString& name)
{
    QVariant qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&name};
    qt_metacall(QMetaObject::InvokeMetaMethod, 46, _a);
    return qax_result;
}

inline void VLCPlugin::pause()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 47, _a);
}

inline void VLCPlugin::play()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 48, _a);
}

inline void VLCPlugin::playFaster()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 49, _a);
}

inline void VLCPlugin::playSlower()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 50, _a);
}

inline void VLCPlugin::playlistClear()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 51, _a);
}

inline void VLCPlugin::playlistNext()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 52, _a);
}

inline void VLCPlugin::playlistPrev()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 53, _a);
}

inline void VLCPlugin::setVariable(const QString& name, const QVariant& value)
{
    void *_a[] = {0, (void*)&name, (void*)&value};
    qt_metacall(QMetaObject::InvokeMetaMethod, 54, _a);
}

inline void VLCPlugin::shuttle(int seconds)
{
    void *_a[] = {0, (void*)&seconds};
    qt_metacall(QMetaObject::InvokeMetaMethod, 55, _a);
}

inline void VLCPlugin::stop()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 56, _a);
}

inline void VLCPlugin::toggleMute()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 57, _a);
}


inline bool VLCPlugin2::AutoLoop() const
{
    QVariant qax_result = property("AutoLoop");
    Q_ASSERT(qax_result.isValid());
    return *(bool*)qax_result.constData();
}
inline void VLCPlugin2::SetAutoLoop(bool value){ setProperty("AutoLoop", QVariant(value)); }

inline bool VLCPlugin2::AutoPlay() const
{
    QVariant qax_result = property("AutoPlay");
    Q_ASSERT(qax_result.isValid());
    return *(bool*)qax_result.constData();
}
inline void VLCPlugin2::SetAutoPlay(bool value){ setProperty("AutoPlay", QVariant(value)); }

inline QColor VLCPlugin2::BackColor() const
{
    QVariant qax_result = property("BackColor");
    Q_ASSERT(qax_result.isValid());
    return *(QColor*)qax_result.constData();
}
inline void VLCPlugin2::SetBackColor(const QColor& value){ setProperty("BackColor", QVariant(value)); }

inline QString VLCPlugin2::BaseURL() const
{
    QVariant qax_result = property("BaseURL");
    Q_ASSERT(qax_result.isValid());
    return *(QString*)qax_result.constData();
}
inline void VLCPlugin2::SetBaseURL(const QString& value){ setProperty("BaseURL", QVariant(value)); }

inline int VLCPlugin2::Length() const
{
    QVariant qax_result = property("Length");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}

inline QString VLCPlugin2::MRL() const
{
    QVariant qax_result = property("MRL");
    Q_ASSERT(qax_result.isValid());
    return *(QString*)qax_result.constData();
}
inline void VLCPlugin2::SetMRL(const QString& value){ setProperty("MRL", QVariant(value)); }

inline bool VLCPlugin2::Playing() const
{
    QVariant qax_result = property("Playing");
    Q_ASSERT(qax_result.isValid());
    return *(bool*)qax_result.constData();
}

inline int VLCPlugin2::PlaylistCount() const
{
    QVariant qax_result = property("PlaylistCount");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}

inline int VLCPlugin2::PlaylistIndex() const
{
    QVariant qax_result = property("PlaylistIndex");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}

inline double VLCPlugin2::Position() const
{
    QVariant qax_result = property("Position");
    Q_ASSERT(qax_result.isValid());
    return *(double*)qax_result.constData();
}
inline void VLCPlugin2::SetPosition(double value){ setProperty("Position", QVariant(value)); }

inline int VLCPlugin2::StartTime() const
{
    QVariant qax_result = property("StartTime");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}
inline void VLCPlugin2::SetStartTime(int value){ setProperty("StartTime", QVariant(value)); }

inline int VLCPlugin2::Time() const
{
    QVariant qax_result = property("Time");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}
inline void VLCPlugin2::SetTime(int value){ setProperty("Time", QVariant(value)); }

inline bool VLCPlugin2::Toolbar() const
{
    QVariant qax_result = property("Toolbar");
    Q_ASSERT(qax_result.isValid());
    return *(bool*)qax_result.constData();
}
inline void VLCPlugin2::SetToolbar(bool value){ setProperty("Toolbar", QVariant(value)); }

inline QString VLCPlugin2::VersionInfo() const
{
    QVariant qax_result = property("VersionInfo");
    Q_ASSERT(qax_result.isValid());
    return *(QString*)qax_result.constData();
}

inline bool VLCPlugin2::Visible() const
{
    QVariant qax_result = property("Visible");
    Q_ASSERT(qax_result.isValid());
    return *(bool*)qax_result.constData();
}
inline void VLCPlugin2::SetVisible(bool value){ setProperty("Visible", QVariant(value)); }

inline int VLCPlugin2::Volume() const
{
    QVariant qax_result = property("Volume");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}
inline void VLCPlugin2::SetVolume(int value){ setProperty("Volume", QVariant(value)); }

inline AXVLC::IVLCAudio* VLCPlugin2::audio() const
{
    AXVLC::IVLCAudio* qax_pointer = 0;
    qRegisterMetaType("IVLCAudio*", &qax_pointer);
    qRegisterMetaType("IVLCAudio", qax_pointer);
    QVariant qax_result = property("audio");
    if (!qax_result.constData()) return 0;
    Q_ASSERT(qax_result.isValid());
    return *(AXVLC::IVLCAudio**)qax_result.constData();
}

inline AXVLC::IVLCInput* VLCPlugin2::input() const
{
    AXVLC::IVLCInput* qax_pointer = 0;
    qRegisterMetaType("IVLCInput*", &qax_pointer);
    qRegisterMetaType("IVLCInput", qax_pointer);
    QVariant qax_result = property("input");
    if (!qax_result.constData()) return 0;
    Q_ASSERT(qax_result.isValid());
    return *(AXVLC::IVLCInput**)qax_result.constData();
}

inline AXVLC::IVLCLog* VLCPlugin2::log() const
{
    AXVLC::IVLCLog* qax_pointer = 0;
    qRegisterMetaType("IVLCLog*", &qax_pointer);
    qRegisterMetaType("IVLCLog", qax_pointer);
    QVariant qax_result = property("log");
    if (!qax_result.constData()) return 0;
    Q_ASSERT(qax_result.isValid());
    return *(AXVLC::IVLCLog**)qax_result.constData();
}

inline AXVLC::IVLCPlaylist* VLCPlugin2::playlist() const
{
    AXVLC::IVLCPlaylist* qax_pointer = 0;
    qRegisterMetaType("IVLCPlaylist*", &qax_pointer);
    qRegisterMetaType("IVLCPlaylist", qax_pointer);
    QVariant qax_result = property("playlist");
    if (!qax_result.constData()) return 0;
    Q_ASSERT(qax_result.isValid());
    return *(AXVLC::IVLCPlaylist**)qax_result.constData();
}

inline AXVLC::IVLCVideo* VLCPlugin2::video() const
{
    AXVLC::IVLCVideo* qax_pointer = 0;
    qRegisterMetaType("IVLCVideo*", &qax_pointer);
    qRegisterMetaType("IVLCVideo", qax_pointer);
    QVariant qax_result = property("video");
    if (!qax_result.constData()) return 0;
    Q_ASSERT(qax_result.isValid());
    return *(AXVLC::IVLCVideo**)qax_result.constData();
}

inline void VLCPlugin2::addTarget(const QString& uri, const QVariant& options, AXVLC::VLCPlaylistMode mode, int Position)
{
    void *_a[] = {0, (void*)&uri, (void*)&options, (void*)&mode, (void*)&Position};
    qt_metacall(QMetaObject::InvokeMetaMethod, 41, _a);
}

inline void VLCPlugin2::fullscreen()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 42, _a);
}

inline QVariant VLCPlugin2::getVariable(const QString& name)
{
    QVariant qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&name};
    qt_metacall(QMetaObject::InvokeMetaMethod, 43, _a);
    return qax_result;
}

inline void VLCPlugin2::pause()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 44, _a);
}

inline void VLCPlugin2::play()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 45, _a);
}

inline void VLCPlugin2::playFaster()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 46, _a);
}

inline void VLCPlugin2::playSlower()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 47, _a);
}

inline void VLCPlugin2::playlistClear()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 48, _a);
}

inline void VLCPlugin2::playlistNext()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 49, _a);
}

inline void VLCPlugin2::playlistPrev()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 50, _a);
}

inline void VLCPlugin2::setVariable(const QString& name, const QVariant& value)
{
    void *_a[] = {0, (void*)&name, (void*)&value};
    qt_metacall(QMetaObject::InvokeMetaMethod, 51, _a);
}

inline void VLCPlugin2::shuttle(int seconds)
{
    void *_a[] = {0, (void*)&seconds};
    qt_metacall(QMetaObject::InvokeMetaMethod, 52, _a);
}

inline void VLCPlugin2::stop()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 53, _a);
}

inline void VLCPlugin2::toggleMute()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 54, _a);
}



#endif

}

template<>
inline void *qMetaTypeConstructHelper(const AXVLC::IVLCControl *t)
{ Q_ASSERT(!t); return new AXVLC::IVLCControl; }

template<>
inline void *qMetaTypeConstructHelper(const AXVLC::IVLCAudio *t)
{ Q_ASSERT(!t); return new AXVLC::IVLCAudio; }

template<>
inline void *qMetaTypeConstructHelper(const AXVLC::IVLCInput *t)
{ Q_ASSERT(!t); return new AXVLC::IVLCInput; }

template<>
inline void *qMetaTypeConstructHelper(const AXVLC::IVLCLog *t)
{ Q_ASSERT(!t); return new AXVLC::IVLCLog; }

template<>
inline void *qMetaTypeConstructHelper(const AXVLC::IVLCMessages *t)
{ Q_ASSERT(!t); return new AXVLC::IVLCMessages; }

template<>
inline void *qMetaTypeConstructHelper(const AXVLC::IVLCMessageIterator *t)
{ Q_ASSERT(!t); return new AXVLC::IVLCMessageIterator; }

template<>
inline void *qMetaTypeConstructHelper(const AXVLC::IVLCMessage *t)
{ Q_ASSERT(!t); return new AXVLC::IVLCMessage; }

template<>
inline void *qMetaTypeConstructHelper(const AXVLC::IVLCPlaylist *t)
{ Q_ASSERT(!t); return new AXVLC::IVLCPlaylist; }

template<>
inline void *qMetaTypeConstructHelper(const AXVLC::IVLCPlaylistItems *t)
{ Q_ASSERT(!t); return new AXVLC::IVLCPlaylistItems; }

template<>
inline void *qMetaTypeConstructHelper(const AXVLC::IVLCVideo *t)
{ Q_ASSERT(!t); return new AXVLC::IVLCVideo; }

template<>
inline void *qMetaTypeConstructHelper(const AXVLC::IVLCControl2 *t)
{ Q_ASSERT(!t); return new AXVLC::IVLCControl2; }

template<>
inline void *qMetaTypeConstructHelper(const AXVLC::VLCPlugin *t)
{ Q_ASSERT(!t); return new AXVLC::VLCPlugin; }

template<>
inline void *qMetaTypeConstructHelper(const AXVLC::VLCPlugin2 *t)
{ Q_ASSERT(!t); return new AXVLC::VLCPlugin2; }

#endif

